namespace THWTicketApp.Web.Services;

public class LocalizationService
{
    private readonly LocalStorageService _localStorage;
    private string _currentLanguage = "de";
    private bool _initialized;

    public event Action? LanguageChanged;
    public string CurrentLanguage => _currentLanguage;

    public LocalizationService(LocalStorageService localStorage)
    {
        _localStorage = localStorage;
    }

    public async Task InitializeAsync()
    {
        if (_initialized) return;
        var lang = await _localStorage.GetItemAsync("settings_language");
        if (!string.IsNullOrEmpty(lang)) _currentLanguage = lang;
        _initialized = true;
    }

    public async Task SetLanguageAsync(string language)
    {
        _currentLanguage = language;
        await _localStorage.SetItemAsync("settings_language", language);
        LanguageChanged?.Invoke();
    }

    public string T(string key) => Get(key, _currentLanguage);

    private static string Get(string key, string lang)
    {
        if (lang == "en" && En.TryGetValue(key, out var en)) return en;
        if (De.TryGetValue(key, out var de)) return de;
        return key;
    }

    private static readonly Dictionary<string, string> De = new()
    {
        // Navigation
        ["nav.dashboard"] = "Dashboard",
        ["nav.tickets"] = "Tickets",
        ["nav.newticket"] = "Neues Ticket",
        ["nav.kanban"] = "Kanban Board",
        ["nav.team"] = "Team",
        ["nav.reports"] = "Berichte",
        ["nav.scanner"] = "Scanner",
        ["nav.notifications"] = "Benachrichtigungen",
        ["nav.syncconflicts"] = "Sync-Konflikte",
        ["nav.settings"] = "Einstellungen",

        // Common
        ["common.save"] = "Speichern",
        ["common.cancel"] = "Abbrechen",
        ["common.delete"] = "Löschen",
        ["common.edit"] = "Bearbeiten",
        ["common.close"] = "Schließen",
        ["common.open"] = "Öffnen",
        ["common.search"] = "Suchen",
        ["common.filter"] = "Filter",
        ["common.refresh"] = "Aktualisieren",
        ["common.loading"] = "Laden...",
        ["common.error"] = "Fehler",
        ["common.success"] = "Erfolgreich",
        ["common.all"] = "Alle",
        ["common.yes"] = "Ja",
        ["common.no"] = "Nein",
        ["common.back"] = "Zurück",
        ["common.logout"] = "Abmelden",

        // Login
        ["login.title"] = "Anmelden",
        ["login.username"] = "Benutzername",
        ["login.password"] = "Passwort",
        ["login.submit"] = "Anmelden",
        ["login.submitting"] = "Anmelden...",
        ["login.failed"] = "Anmeldung fehlgeschlagen. Bitte Benutzername und Passwort prüfen.",
        ["login.connection_error"] = "Verbindungsfehler",
        ["login.passkey"] = "Mit Passkey anmelden",
        ["login.passkey_failed"] = "Passkey-Anmeldung fehlgeschlagen.",
        ["login.username_required"] = "Benutzername ist erforderlich",
        ["login.password_required"] = "Passwort ist erforderlich",

        // Tickets
        ["tickets.title"] = "Tickets",
        ["tickets.new"] = "Neues Ticket",
        ["tickets.search"] = "Tickets suchen...",
        ["tickets.open"] = "Offen",
        ["tickets.pending"] = "In Bearbeitung",
        ["tickets.closed"] = "Geschlossen",
        ["tickets.mytickets"] = "Meine Tickets",
        ["tickets.sort"] = "Sortierung",
        ["tickets.sort.newest"] = "Erstellt (neueste)",
        ["tickets.sort.oldest"] = "Erstellt (älteste)",
        ["tickets.sort.updated"] = "Zuletzt aktualisiert",
        ["tickets.sort.priority"] = "Priorität",
        ["tickets.sort.subject"] = "Betreff (A-Z)",
        ["tickets.none"] = "Keine Tickets gefunden.",
        ["tickets.assigned"] = "Ticket zugewiesen.",
        ["tickets.closed_success"] = "Ticket geschlossen.",
        ["tickets.savefilter"] = "Filter speichern",
        ["tickets.loadfilter"] = "Gespeicherte Filter",
        ["tickets.deletefilter"] = "Filter löschen",
        ["tickets.filtername"] = "Filtername",

        // Ticket Detail
        ["detail.description"] = "Beschreibung",
        ["detail.no_description"] = "Keine Beschreibung.",
        ["detail.edit"] = "Ticket bearbeiten",
        ["detail.subject"] = "Betreff",
        ["detail.status"] = "Status",
        ["detail.priority"] = "Priorität",
        ["detail.creator"] = "Ersteller",
        ["detail.assignee"] = "Zuständig",
        ["detail.unassigned"] = "Nicht zugewiesen",
        ["detail.group"] = "Gruppe",
        ["detail.type"] = "Typ",
        ["detail.created"] = "Erstellt",
        ["detail.updated"] = "Aktualisiert",
        ["detail.due"] = "Fällig",
        ["detail.assign_to"] = "Zuweisen an",
        ["detail.assign"] = "Zuweisen",
        ["detail.remove_assign"] = "Entfernen",
        ["detail.tags"] = "Tags",
        ["detail.linked"] = "Verknüpfte Tickets",
        ["detail.no_links"] = "Keine Verknüpfungen.",
        ["detail.link_related"] = "Verwandt",
        ["detail.link_blocks"] = "Blockiert",
        ["detail.link_blocked_by"] = "Blockiert von",
        ["detail.link_duplicate"] = "Duplikat",
        ["detail.subscribe"] = "Abonnieren",
        ["detail.unsubscribe"] = "Abbestellen",
        ["detail.subscribed"] = "Ticket abonniert.",
        ["detail.unsubscribed"] = "Abo entfernt.",
        ["detail.delete_ticket"] = "Ticket löschen",
        ["detail.not_found"] = "Ticket nicht gefunden.",

        // Comments & Notes
        ["comments.title"] = "Kommentare",
        ["comments.new"] = "Neuer Kommentar",
        ["comments.send"] = "Kommentar senden",
        ["comments.added"] = "Kommentar hinzugefügt.",
        ["comments.quickreply"] = "Schnellantwort einfügen",
        ["comments.mention"] = "Erwähnen",
        ["notes.title"] = "Notizen",
        ["notes.new"] = "Neue Notiz",
        ["notes.add"] = "Notiz hinzufügen",
        ["notes.added"] = "Notiz hinzugefügt.",

        // Attachments
        ["attachments.title"] = "Anhänge",
        ["attachments.none"] = "Keine Anhänge.",
        ["attachments.upload"] = "Datei hochladen",
        ["attachments.uploading"] = "Wird hochgeladen...",
        ["attachments.uploaded"] = "Datei hochgeladen.",
        ["attachments.deleted"] = "Anhang gelöscht.",
        ["attachments.name"] = "Name",
        ["attachments.type"] = "Typ",
        ["attachments.size"] = "Größe",
        ["attachments.date"] = "Datum",
        ["attachments.actions"] = "Aktionen",

        // Time Tracking
        ["time.title"] = "Zeiterfassung",
        ["time.timer"] = "Timer",
        ["time.start"] = "Starten",
        ["time.stop"] = "Stoppen",
        ["time.description"] = "Beschreibung (optional)",
        ["time.total"] = "Gesamt",
        ["time.no_entries"] = "Keine Zeiteinträge.",
        ["time.col_start"] = "Start",
        ["time.col_duration"] = "Dauer",
        ["time.col_description"] = "Beschreibung",

        // History
        ["history.title"] = "Verlauf",

        // Assets
        ["nav.assets"] = "Ausstattung",
        ["assets.new"] = "Neues Asset",
        ["assets.name"] = "Name",
        ["assets.tag"] = "Asset-Tag",
        ["assets.category"] = "Kategorie",
        ["assets.location"] = "Standort",
        ["assets.none"] = "Keine Assets vorhanden.",
        ["assets.name_required"] = "Name ist erforderlich.",
        ["assets.delete_confirm"] = "Asset wirklich löschen?",
        ["assets.link_ticket"] = "Mit Ticket verknüpfen",
        ["assets.link_ticket_prompt"] = "Ticket-Nummer",
        ["assets.link_ticket_empty"] = "Bitte Ticket-Nummer eingeben.",
        ["assets.link_ticket_success"] = "Asset mit Ticket verknüpft.",
        ["assets.link_ticket_failed"] = "Verknüpfung fehlgeschlagen.",

        // Templates
        ["nav.templates"] = "Ticket-Vorlagen",
        ["templates.new"] = "Neue Vorlage",
        ["templates.none"] = "Keine Vorlagen vorhanden.",
        ["templates.name"] = "Name",
        ["templates.subject"] = "Betreff",
        ["templates.issue"] = "Beschreibung",
        ["templates.issue_preview"] = "Beschreibung",
        ["templates.name_required"] = "Name ist erforderlich.",
        ["templates.subject_required"] = "Betreff ist erforderlich.",
        ["templates.delete_confirm"] = "Vorlage wirklich löschen?",

        // Calendar
        ["nav.calendar"] = "Kalender",
        ["calendar.from"] = "Von",
        ["calendar.to"] = "Bis",
        ["calendar.load"] = "Laden",
        ["calendar.this_month"] = "Aktueller Monat",
        ["calendar.none"] = "Keine Ereignisse im gewählten Zeitraum.",
        ["calendar.range_required"] = "Bitte Start- und Enddatum wählen.",
        ["calendar.range_invalid"] = "Das Enddatum muss nach dem Startdatum liegen.",
        ["calendar.ticket_deadline"] = "Ticket-Frist",
        ["calendar.recurring_task"] = "Wiederkehrende Aufgabe",
        ["calendar.open_ticket"] = "Ticket öffnen",

        // Recurring Tasks
        ["nav.recurring"] = "Wiederkehrende Aufgaben",
        ["recurring.new"] = "Neue Aufgabe",
        ["recurring.active"] = "Aktiv",
        ["recurring.inactive"] = "Inaktiv",
        ["recurring.schedule"] = "Zeitplan",
        ["recurring.ticket_subject"] = "Ticket-Betreff",
        ["recurring.ticket_template"] = "Ticket-Vorlage",
        ["recurring.schedule_type"] = "Wiederholungsart",
        ["recurring.monthly"] = "Monatlich",
        ["recurring.quarterly"] = "Quartalsweise",
        ["recurring.annual"] = "Jährlich",
        ["recurring.day_of_month"] = "Tag im Monat",
        ["recurring.days_before"] = "Tage vor Fälligkeit",
        ["recurring.enabled"] = "Aktiviert",
        ["recurring.next_run"] = "Nächste Ausführung",
        ["recurring.none"] = "Keine wiederkehrenden Aufgaben.",
        ["recurring.name_required"] = "Name ist erforderlich.",
        ["recurring.delete_confirm"] = "Aufgabe wirklich löschen?",

        // Reports
        ["reports.handover"] = "Übergabebericht",
        ["reports.sitzung"] = "OV-Sitzungsbericht",

        // Settings
        ["settings.title"] = "Einstellungen",
        ["settings.appearance"] = "Erscheinungsbild",
        ["settings.darkmode"] = "Dark Mode",
        ["settings.notifications"] = "Benachrichtigungen",
        ["settings.notifications_desc"] = "Über neue Tickets und Änderungen informieren",
        ["settings.notify_new"] = "Neue Tickets",
        ["settings.notify_comments"] = "Kommentare",
        ["settings.notify_status"] = "Statusänderungen",
        ["settings.notify_mine"] = "Nur meine Tickets",
        ["settings.notify_mine_desc"] = "Nur bei mir zugewiesenen Tickets",
        ["settings.notify_highprio"] = "Nur hohe Priorität",
        ["settings.notify_highprio_desc"] = "Nur bei hoher/dringender Priorität",
        ["settings.language"] = "Sprache / Language",
        ["settings.api"] = "API-Konfiguration",
        ["settings.api_url"] = "Server-URL",
        ["settings.timeout"] = "Verbindungs-Timeout (Sekunden)",
        ["settings.test_connection"] = "Verbindung testen",
        ["settings.testing"] = "Teste...",
        ["settings.cache"] = "Offline-Cache",
        ["settings.cache_enable"] = "Offline-Caching aktivieren",
        ["settings.cache_desc"] = "Tickets lokal speichern für Offline-Zugriff",
        ["settings.cache_clear"] = "Cache leeren",
        ["settings.saved"] = "Einstellungen gespeichert.",
        ["settings.passkey"] = "Passkey / Biometrie",
        ["settings.passkey_register"] = "Passkey registrieren",
        ["settings.passkey_registered"] = "Passkey registriert",
        ["settings.passkey_remove"] = "Passkey entfernen",
        ["settings.passkey_desc"] = "Schnelle Anmeldung per Fingerabdruck, Gesicht oder Geräte-PIN",
        ["settings.passkey_not_supported"] = "Ihr Browser unterstützt keine Passkeys.",
        ["settings.passkey_register_failed"] = "Passkey-Registrierung fehlgeschlagen.",
        ["settings.passkey_removed"] = "Passkey entfernt.",
        ["settings.timeout_invalid"] = "Timeout muss zwischen 5 und 300 Sekunden liegen.",
        ["settings.connection_testing"] = "Teste Verbindung...",
        ["settings.connection_success"] = "Verbindung erfolgreich!",
        ["settings.connection_timeout"] = "Zeitüberschreitung. Server antwortet nicht.",
        ["settings.connection_failed"] = "Verbindung fehlgeschlagen. Server nicht erreichbar.",
        ["settings.cache_cleared"] = "Cache geleert.",
        ["settings.about"] = "Über",
        ["settings.synclog"] = "Sync-Log",
        ["settings.synclog_desc"] = "Protokoll der Offline-Synchronisierung",
        ["settings.synclog_empty"] = "Keine Log-Einträge vorhanden.",
        ["settings.synclog_export"] = "Log exportieren",
        ["settings.synclog_clear"] = "Log leeren",
        ["settings.synclog_cleared"] = "Sync-Log geleert.",
        ["settings.synclog_time"] = "Zeitpunkt",
        ["settings.synclog_level"] = "Stufe",
        ["settings.synclog_action"] = "Aktion",
        ["settings.synclog_message"] = "Nachricht",

        // Batch
        ["batch.toggle"] = "Mehrfachauswahl",
        ["batch.selected"] = "{0} Ticket(s) ausgewählt",
        ["batch.deleted"] = "{0} gelöscht, {1} fehlgeschlagen",
        ["batch.updated"] = "{0} aktualisiert, {1} fehlgeschlagen",

        // Kanban
        ["kanban.board"] = "Kanban-Board",
        ["kanban.tickets"] = "Tickets",
        ["kanban.ticket_moved"] = "Ticket verschoben",
        ["kanban.move_failed"] = "Status-Änderung fehlgeschlagen.",
        ["kanban.no_subject"] = "(Kein Betreff)",
        ["common.unknown"] = "Unbekannt",
        ["common.or"] = "oder",
        ["common.network_error"] = "Netzwerkfehler. Bitte erneut versuchen.",

        // Ticket Detail (additional)
        ["detail.details"] = "Details",
        ["detail.ticket_updated"] = "Ticket aktualisiert.",
        ["detail.update_failed"] = "Aktualisierung fehlgeschlagen.",
        ["detail.assign_updated"] = "Zuweisung aktualisiert.",
        ["detail.assign_failed"] = "Zuweisung fehlgeschlagen.",
        ["detail.assign_removed"] = "Zuweisung entfernt.",
        ["detail.add_failed"] = "Fehler beim Hinzufügen.",
        ["detail.delete_failed"] = "Löschen fehlgeschlagen.",
        ["detail.ticket_deleted"] = "Ticket gelöscht.",
        ["detail.templates_saved"] = "Vorlagen gespeichert.",
        ["detail.edit_templates"] = "Vorlagen bearbeiten",
        ["detail.quickreply_templates"] = "Schnellantwort-Vorlagen",
        ["detail.new_template"] = "Neu",
        ["detail.link_ticket_num"] = "Ticket #",
        ["common.add"] = "Hinzufügen",

        // Checklist
        ["checklist.title"] = "Checkliste",
        ["checklist.empty"] = "Keine Einträge.",
        ["checklist.new_item"] = "Neuer Eintrag",

        ["detail.add_tag"] = "Tag hinzufügen",
        ["detail.tag_added"] = "Tag hinzugefügt",
        ["detail.tag_removed"] = "Tag entfernt.",

        // Tickets (additional)
        ["tickets.assign_me"] = "Mir zuweisen",
        ["tickets.actions"] = "Ticket-Aktionen",
        ["tickets.assign_failed"] = "Zuweisung fehlgeschlagen.",
        ["tickets.close_failed"] = "Schließen fehlgeschlagen.",
        ["tickets.filter_saved"] = "Filter gespeichert.",
        ["tickets.filter_deleted"] = "Filter gelöscht.",
        ["tickets.create_title"] = "Neues Ticket erstellen",
        ["tickets.subject_required"] = "Betreff ist erforderlich",
        ["tickets.description_required"] = "Beschreibung ist erforderlich",
        ["tickets.group_required"] = "Gruppe ist erforderlich",
        ["tickets.create"] = "Ticket erstellen",
        ["tickets.form_load_error"] = "Fehler beim Laden der Formulardaten.",
        ["tickets.created"] = "Ticket erstellt!",
        ["tickets.server_rejected"] = "Server hat das Ticket abgelehnt.",

        // Dashboard
        ["dashboard.total"] = "Gesamt",
        ["dashboard.open"] = "Offen",
        ["dashboard.in_progress"] = "In Bearbeitung",
        ["dashboard.closed"] = "Geschlossen",
        ["dashboard.mine"] = "Meine",
        ["dashboard.overdue"] = "Überfällig",
        ["dashboard.recent"] = "Letzte Tickets",
        ["dashboard.view_all"] = "Alle anzeigen",
        ["dashboard.no_tickets"] = "Keine Tickets vorhanden.",
        ["dashboard.quick_actions"] = "Schnellaktionen",
        ["dashboard.tickets_per_group"] = "Tickets pro Gruppe",
        ["dashboard.open_suffix"] = "offen",
        ["dashboard.welcome"] = "Willkommen!",
        ["dashboard.welcome_user"] = "Willkommen",

        // Login (additional)
        ["login.configure_server"] = "Bitte zuerst die Server-URL konfigurieren.",
        ["login.server_config"] = "Server-Konfiguration",
        ["login.server_url"] = "Server-URL",
        ["login.save_url"] = "URL speichern",
        ["login.invalid_url"] = "Bitte eine gültige Server-URL eingeben.",
        ["login.passkey_cancelled"] = "Passkey-Anmeldung abgebrochen.",

        // Scanner
        ["scanner.instruction"] = "Scannen Sie einen QR-Code oder Barcode, um ein Ticket zu öffnen.",
        ["scanner.not_supported"] = "Ihr Browser unterstützt die BarcodeDetector API nicht. Bitte geben Sie die Ticket-Nummer manuell ein.",
        ["scanner.start_camera"] = "Kamera starten",
        ["scanner.stop_camera"] = "Kamera stoppen",
        ["scanner.manual_input"] = "Manuelle Eingabe",
        ["scanner.ticket_number"] = "Ticket-Nummer",
        ["scanner.open_ticket"] = "Öffnen",
        ["scanner.camera_failed"] = "Kamera konnte nicht gestartet werden.",
        ["scanner.detected"] = "Erkannt",

        // Sync Conflicts
        ["sync.no_conflicts"] = "Keine Sync-Konflikte vorhanden.",
        ["sync.conflicts_found"] = "{0} Konflikte gefunden. Bitte entscheiden Sie für jede Aktion, ob sie trotzdem angewendet oder verworfen werden soll.",
        ["sync.force_apply"] = "Trotzdem anwenden",
        ["sync.discard"] = "Verwerfen",
        ["sync.applied"] = "Aktion erfolgreich angewendet.",
        ["sync.apply_failed"] = "Aktion konnte nicht angewendet werden.",
        ["sync.discarded"] = "Aktion verworfen.",
        ["sync.type_deleted"] = "Ticket gelöscht",
        ["sync.type_permission"] = "Keine Berechtigung",
        ["sync.type_status"] = "Status bereits geändert",
        ["sync.type_updated"] = "Ticket bearbeitet",
        ["sync.type_conflict"] = "Konflikt",
        ["sync.advice_deleted"] = "Da das Ticket serverseitig nicht mehr existiert, kann die Aktion nur verworfen werden.",
        ["sync.advice_permission"] = "Deine Berechtigung für dieses Ticket wurde entzogen. Bitte wende dich an einen Administrator.",
        ["sync.advice_status"] = "Jemand anderes hat den Status in der Zwischenzeit gesetzt. Erzwingen überschreibt diesen Wert.",
        ["sync.action_add_comment"] = "Kommentar hinzufügen",
        ["sync.action_add_note"] = "Notiz hinzufügen",
        ["sync.action_assign"] = "Ticket zuweisen",
        ["sync.action_update_status"] = "Status ändern",
        ["sync.action_create"] = "Neues Ticket erstellen",
        ["sync.action_clear_assignee"] = "Zuweisung entfernen",
        ["sync.action_update_fields"] = "Ticket-Felder aktualisieren",
        ["sync.action_delete"] = "Ticket löschen",
        ["sync.action_upload"] = "Anhang hochladen",

        // Team
        ["team.members"] = "Mitglieder",
        ["team.tickets_per_person"] = "Tickets/Person",
        ["team.tickets_30d"] = "Tickets (30T)",
        ["team.closed"] = "Geschlossen",
        ["team.response_time"] = "Antwortzeit",
        ["team.overdue"] = "Überfällig",
        ["team.most_requests"] = "Meiste Anfragen",
        ["team.most_assignments"] = "Meiste Zuweisungen",
        ["team.workload"] = "Teamauslastung",
        ["team.no_members"] = "Keine Teammitglieder gefunden.",
        ["team.assigned"] = "Zugewiesen",
        ["team.open"] = "Offen",
        ["team.workload_col"] = "Auslastung",
        ["team.workload_high"] = "Hoch",
        ["team.workload_medium"] = "Mittel",
        ["team.workload_normal"] = "Normal",

        // Notifications
        ["notifications.unread"] = "Ungelesen",
        ["notifications.read"] = "Gelesen",
        ["notifications.none"] = "Keine Benachrichtigungen vorhanden.",
        ["notifications.default_title"] = "Benachrichtigung",
        ["notifications.load_more"] = "Mehr laden",

        // Reports
        ["reports.weekly_trend"] = "Ticket-Trend (letzte 8 Wochen)",
        ["reports.created"] = "Erstellt",
        ["reports.closed"] = "Geschlossen",
        ["reports.no_data"] = "Keine Daten vorhanden.",
        ["reports.resolution_times"] = "Auflösungszeiten",
        ["reports.resolved"] = "Gelöste Tickets",
        ["reports.average"] = "Durchschnitt",
        ["reports.fastest"] = "Schnellste",
        ["reports.slowest"] = "Langsamste",
        ["reports.sla_compliance"] = "SLA-Einhaltung",
        ["reports.sla_met"] = "Eingehalten",
        ["reports.sla_breached"] = "Überschritten",
        ["reports.sla_at_risk"] = "Gefährdet",
        ["reports.no_deadline"] = "Ohne Frist",
        ["reports.priority_dist"] = "Prioritätsverteilung",
        ["reports.top_assignees"] = "Top Bearbeiter",
        ["reports.no_deadline_tickets"] = "Keine Tickets mit Fälligkeitsdatum",

        // Accessibility
        ["a11y.toggle_menu"] = "Menü umschalten",
        ["a11y.notifications"] = "Benachrichtigungen",
        ["a11y.toggle_darkmode"] = "Dark Mode umschalten",
        ["a11y.logout"] = "Abmelden",
        ["a11y.main_navigation"] = "Hauptnavigation",
    };

    private static readonly Dictionary<string, string> En = new()
    {
        // Navigation
        ["nav.dashboard"] = "Dashboard",
        ["nav.tickets"] = "Tickets",
        ["nav.newticket"] = "New Ticket",
        ["nav.kanban"] = "Kanban Board",
        ["nav.team"] = "Team",
        ["nav.reports"] = "Reports",
        ["nav.scanner"] = "Scanner",
        ["nav.notifications"] = "Notifications",
        ["nav.syncconflicts"] = "Sync Conflicts",
        ["nav.settings"] = "Settings",

        // Common
        ["common.save"] = "Save",
        ["common.cancel"] = "Cancel",
        ["common.delete"] = "Delete",
        ["common.edit"] = "Edit",
        ["common.close"] = "Close",
        ["common.open"] = "Open",
        ["common.search"] = "Search",
        ["common.filter"] = "Filter",
        ["common.refresh"] = "Refresh",
        ["common.loading"] = "Loading...",
        ["common.error"] = "Error",
        ["common.success"] = "Success",
        ["common.all"] = "All",
        ["common.yes"] = "Yes",
        ["common.no"] = "No",
        ["common.back"] = "Back",
        ["common.logout"] = "Logout",

        // Login
        ["login.title"] = "Sign In",
        ["login.username"] = "Username",
        ["login.password"] = "Password",
        ["login.submit"] = "Sign In",
        ["login.submitting"] = "Signing in...",
        ["login.failed"] = "Login failed. Please check your username and password.",
        ["login.connection_error"] = "Connection error",
        ["login.passkey"] = "Sign in with Passkey",
        ["login.passkey_failed"] = "Passkey authentication failed.",
        ["login.username_required"] = "Username is required",
        ["login.password_required"] = "Password is required",

        // Tickets
        ["tickets.title"] = "Tickets",
        ["tickets.new"] = "New Ticket",
        ["tickets.search"] = "Search tickets...",
        ["tickets.open"] = "Open",
        ["tickets.pending"] = "In Progress",
        ["tickets.closed"] = "Closed",
        ["tickets.mytickets"] = "My Tickets",
        ["tickets.sort"] = "Sort by",
        ["tickets.sort.newest"] = "Created (newest)",
        ["tickets.sort.oldest"] = "Created (oldest)",
        ["tickets.sort.updated"] = "Last updated",
        ["tickets.sort.priority"] = "Priority",
        ["tickets.sort.subject"] = "Subject (A-Z)",
        ["tickets.none"] = "No tickets found.",
        ["tickets.assigned"] = "Ticket assigned.",
        ["tickets.closed_success"] = "Ticket closed.",
        ["tickets.savefilter"] = "Save Filter",
        ["tickets.loadfilter"] = "Saved Filters",
        ["tickets.deletefilter"] = "Delete Filter",
        ["tickets.filtername"] = "Filter name",

        // Ticket Detail
        ["detail.description"] = "Description",
        ["detail.no_description"] = "No description.",
        ["detail.edit"] = "Edit ticket",
        ["detail.subject"] = "Subject",
        ["detail.status"] = "Status",
        ["detail.priority"] = "Priority",
        ["detail.creator"] = "Creator",
        ["detail.assignee"] = "Assignee",
        ["detail.unassigned"] = "Unassigned",
        ["detail.group"] = "Group",
        ["detail.type"] = "Type",
        ["detail.created"] = "Created",
        ["detail.updated"] = "Updated",
        ["detail.due"] = "Due",
        ["detail.assign_to"] = "Assign to",
        ["detail.assign"] = "Assign",
        ["detail.remove_assign"] = "Remove",
        ["detail.tags"] = "Tags",
        ["detail.linked"] = "Linked Tickets",
        ["detail.no_links"] = "No links.",
        ["detail.link_related"] = "Related",
        ["detail.link_blocks"] = "Blocks",
        ["detail.link_blocked_by"] = "Blocked by",
        ["detail.link_duplicate"] = "Duplicate",
        ["detail.subscribe"] = "Subscribe",
        ["detail.unsubscribe"] = "Unsubscribe",
        ["detail.subscribed"] = "Subscribed to ticket.",
        ["detail.unsubscribed"] = "Unsubscribed from ticket.",
        ["detail.delete_ticket"] = "Delete ticket",
        ["detail.not_found"] = "Ticket not found.",

        // Comments & Notes
        ["comments.title"] = "Comments",
        ["comments.new"] = "New comment",
        ["comments.send"] = "Send comment",
        ["comments.added"] = "Comment added.",
        ["comments.quickreply"] = "Insert quick reply",
        ["comments.mention"] = "Mention",
        ["notes.title"] = "Notes",
        ["notes.new"] = "New note",
        ["notes.add"] = "Add note",
        ["notes.added"] = "Note added.",

        // Attachments
        ["attachments.title"] = "Attachments",
        ["attachments.none"] = "No attachments.",
        ["attachments.upload"] = "Upload file",
        ["attachments.uploading"] = "Uploading...",
        ["attachments.uploaded"] = "File uploaded.",
        ["attachments.deleted"] = "Attachment deleted.",
        ["attachments.name"] = "Name",
        ["attachments.type"] = "Type",
        ["attachments.size"] = "Size",
        ["attachments.date"] = "Date",
        ["attachments.actions"] = "Actions",

        // Time Tracking
        ["time.title"] = "Time Tracking",
        ["time.timer"] = "Timer",
        ["time.start"] = "Start",
        ["time.stop"] = "Stop",
        ["time.description"] = "Description (optional)",
        ["time.total"] = "Total",
        ["time.no_entries"] = "No time entries.",
        ["time.col_start"] = "Start",
        ["time.col_duration"] = "Duration",
        ["time.col_description"] = "Description",

        // History
        ["history.title"] = "History",

        // Assets
        ["nav.assets"] = "Assets",
        ["assets.new"] = "New Asset",
        ["assets.name"] = "Name",
        ["assets.tag"] = "Asset Tag",
        ["assets.category"] = "Category",
        ["assets.location"] = "Location",
        ["assets.none"] = "No assets found.",
        ["assets.name_required"] = "Name is required.",
        ["assets.delete_confirm"] = "Really delete asset",
        ["assets.link_ticket"] = "Link to ticket",
        ["assets.link_ticket_prompt"] = "Ticket number",
        ["assets.link_ticket_empty"] = "Please enter a ticket number.",
        ["assets.link_ticket_success"] = "Asset linked to ticket.",
        ["assets.link_ticket_failed"] = "Linking failed.",

        // Templates
        ["nav.templates"] = "Ticket Templates",
        ["templates.new"] = "New Template",
        ["templates.none"] = "No templates yet.",
        ["templates.name"] = "Name",
        ["templates.subject"] = "Subject",
        ["templates.issue"] = "Description",
        ["templates.issue_preview"] = "Description",
        ["templates.name_required"] = "Name is required.",
        ["templates.subject_required"] = "Subject is required.",
        ["templates.delete_confirm"] = "Really delete template?",

        // Calendar
        ["nav.calendar"] = "Calendar",
        ["calendar.from"] = "From",
        ["calendar.to"] = "To",
        ["calendar.load"] = "Load",
        ["calendar.this_month"] = "Current month",
        ["calendar.none"] = "No events in the selected range.",
        ["calendar.range_required"] = "Please pick a start and end date.",
        ["calendar.range_invalid"] = "End date must be after start date.",
        ["calendar.ticket_deadline"] = "Ticket deadline",
        ["calendar.recurring_task"] = "Recurring task",
        ["calendar.open_ticket"] = "Open ticket",

        // Recurring Tasks
        ["nav.recurring"] = "Recurring Tasks",
        ["recurring.new"] = "New Task",
        ["recurring.active"] = "Active",
        ["recurring.inactive"] = "Inactive",
        ["recurring.schedule"] = "Schedule",
        ["recurring.ticket_subject"] = "Ticket Subject",
        ["recurring.ticket_template"] = "Ticket Template",
        ["recurring.schedule_type"] = "Recurrence Type",
        ["recurring.monthly"] = "Monthly",
        ["recurring.quarterly"] = "Quarterly",
        ["recurring.annual"] = "Annual",
        ["recurring.day_of_month"] = "Day of Month",
        ["recurring.days_before"] = "Days before deadline",
        ["recurring.enabled"] = "Enabled",
        ["recurring.next_run"] = "Next Run",
        ["recurring.none"] = "No recurring tasks.",
        ["recurring.name_required"] = "Name is required.",
        ["recurring.delete_confirm"] = "Really delete task",

        // Reports
        ["reports.handover"] = "Handover Report",
        ["reports.sitzung"] = "Meeting Report",

        // Settings
        ["settings.title"] = "Settings",
        ["settings.appearance"] = "Appearance",
        ["settings.darkmode"] = "Dark Mode",
        ["settings.notifications"] = "Notifications",
        ["settings.notifications_desc"] = "Get notified about new tickets and changes",
        ["settings.notify_new"] = "New tickets",
        ["settings.notify_comments"] = "Comments",
        ["settings.notify_status"] = "Status changes",
        ["settings.notify_mine"] = "My tickets only",
        ["settings.notify_mine_desc"] = "Only for tickets assigned to me",
        ["settings.notify_highprio"] = "High priority only",
        ["settings.notify_highprio_desc"] = "Only for high/urgent priority",
        ["settings.language"] = "Language / Sprache",
        ["settings.api"] = "API Configuration",
        ["settings.api_url"] = "Server URL",
        ["settings.timeout"] = "Connection timeout (seconds)",
        ["settings.test_connection"] = "Test connection",
        ["settings.testing"] = "Testing...",
        ["settings.cache"] = "Offline Cache",
        ["settings.cache_enable"] = "Enable offline caching",
        ["settings.cache_desc"] = "Store tickets locally for offline access",
        ["settings.cache_clear"] = "Clear cache",
        ["settings.saved"] = "Settings saved.",
        ["settings.passkey"] = "Passkey / Biometrics",
        ["settings.passkey_register"] = "Register Passkey",
        ["settings.passkey_registered"] = "Passkey registered",
        ["settings.passkey_remove"] = "Remove Passkey",
        ["settings.passkey_desc"] = "Quick sign-in via fingerprint, face, or device PIN",
        ["settings.passkey_not_supported"] = "Your browser does not support passkeys.",
        ["settings.passkey_register_failed"] = "Passkey registration failed.",
        ["settings.passkey_removed"] = "Passkey removed.",
        ["settings.timeout_invalid"] = "Timeout must be between 5 and 300 seconds.",
        ["settings.connection_testing"] = "Testing connection...",
        ["settings.connection_success"] = "Connection successful!",
        ["settings.connection_timeout"] = "Timeout. Server is not responding.",
        ["settings.connection_failed"] = "Connection failed. Server unreachable.",
        ["settings.cache_cleared"] = "Cache cleared.",
        ["settings.about"] = "About",
        ["settings.synclog"] = "Sync Log",
        ["settings.synclog_desc"] = "Offline synchronization activity log",
        ["settings.synclog_empty"] = "No log entries.",
        ["settings.synclog_export"] = "Export log",
        ["settings.synclog_clear"] = "Clear log",
        ["settings.synclog_cleared"] = "Sync log cleared.",
        ["settings.synclog_time"] = "Time",
        ["settings.synclog_level"] = "Level",
        ["settings.synclog_action"] = "Action",
        ["settings.synclog_message"] = "Message",

        // Batch
        ["batch.toggle"] = "Multi-select",
        ["batch.selected"] = "{0} ticket(s) selected",
        ["batch.deleted"] = "{0} deleted, {1} failed",
        ["batch.updated"] = "{0} updated, {1} failed",

        // Kanban
        ["kanban.board"] = "Kanban board",
        ["kanban.tickets"] = "tickets",
        ["kanban.ticket_moved"] = "Ticket moved",
        ["kanban.move_failed"] = "Status change failed.",
        ["kanban.no_subject"] = "(No subject)",
        ["common.unknown"] = "Unknown",
        ["common.or"] = "or",
        ["common.network_error"] = "Network error. Please try again.",

        // Ticket Detail (additional)
        ["detail.details"] = "Details",
        ["detail.ticket_updated"] = "Ticket updated.",
        ["detail.update_failed"] = "Update failed.",
        ["detail.assign_updated"] = "Assignment updated.",
        ["detail.assign_failed"] = "Assignment failed.",
        ["detail.assign_removed"] = "Assignment removed.",
        ["detail.add_failed"] = "Failed to add.",
        ["detail.delete_failed"] = "Delete failed.",
        ["detail.ticket_deleted"] = "Ticket deleted.",
        ["detail.templates_saved"] = "Templates saved.",
        ["detail.edit_templates"] = "Edit templates",
        ["detail.quickreply_templates"] = "Quick reply templates",
        ["detail.new_template"] = "New",
        ["detail.link_ticket_num"] = "Ticket #",
        ["common.add"] = "Add",

        // Checklist
        ["checklist.title"] = "Checklist",
        ["checklist.empty"] = "No items.",
        ["checklist.new_item"] = "New item",

        ["detail.add_tag"] = "Add tag",
        ["detail.tag_added"] = "Tag added",
        ["detail.tag_removed"] = "Tag removed.",

        // Tickets (additional)
        ["tickets.assign_me"] = "Assign to me",
        ["tickets.actions"] = "Ticket actions",
        ["tickets.assign_failed"] = "Assignment failed.",
        ["tickets.close_failed"] = "Close failed.",
        ["tickets.filter_saved"] = "Filter saved.",
        ["tickets.filter_deleted"] = "Filter deleted.",
        ["tickets.create_title"] = "Create new ticket",
        ["tickets.subject_required"] = "Subject is required",
        ["tickets.description_required"] = "Description is required",
        ["tickets.group_required"] = "Group is required",
        ["tickets.create"] = "Create ticket",
        ["tickets.form_load_error"] = "Failed to load form data.",
        ["tickets.created"] = "Ticket created!",
        ["tickets.server_rejected"] = "Server rejected the ticket.",

        // Dashboard
        ["dashboard.total"] = "Total",
        ["dashboard.open"] = "Open",
        ["dashboard.in_progress"] = "In Progress",
        ["dashboard.closed"] = "Closed",
        ["dashboard.mine"] = "Mine",
        ["dashboard.overdue"] = "Overdue",
        ["dashboard.recent"] = "Recent Tickets",
        ["dashboard.view_all"] = "View all",
        ["dashboard.no_tickets"] = "No tickets found.",
        ["dashboard.quick_actions"] = "Quick Actions",
        ["dashboard.tickets_per_group"] = "Tickets per Group",
        ["dashboard.open_suffix"] = "open",
        ["dashboard.welcome"] = "Welcome!",
        ["dashboard.welcome_user"] = "Welcome",

        // Login (additional)
        ["login.configure_server"] = "Please configure the server URL first.",
        ["login.server_config"] = "Server Configuration",
        ["login.server_url"] = "Server URL",
        ["login.save_url"] = "Save URL",
        ["login.invalid_url"] = "Please enter a valid server URL.",
        ["login.passkey_cancelled"] = "Passkey authentication cancelled.",

        // Scanner
        ["scanner.instruction"] = "Scan a QR code or barcode to open a ticket.",
        ["scanner.not_supported"] = "Your browser does not support the BarcodeDetector API. Please enter the ticket number manually.",
        ["scanner.start_camera"] = "Start camera",
        ["scanner.stop_camera"] = "Stop camera",
        ["scanner.manual_input"] = "Manual input",
        ["scanner.ticket_number"] = "Ticket number",
        ["scanner.open_ticket"] = "Open",
        ["scanner.camera_failed"] = "Camera could not be started.",
        ["scanner.detected"] = "Detected",

        // Sync Conflicts
        ["sync.no_conflicts"] = "No sync conflicts.",
        ["sync.conflicts_found"] = "{0} conflicts found. Please decide for each action whether to force-apply or discard.",
        ["sync.force_apply"] = "Force apply",
        ["sync.discard"] = "Discard",
        ["sync.applied"] = "Action applied successfully.",
        ["sync.apply_failed"] = "Action could not be applied.",
        ["sync.discarded"] = "Action discarded.",
        ["sync.type_deleted"] = "Ticket deleted",
        ["sync.type_permission"] = "No permission",
        ["sync.type_status"] = "Status already changed",
        ["sync.type_updated"] = "Ticket updated",
        ["sync.type_conflict"] = "Conflict",
        ["sync.advice_deleted"] = "The ticket no longer exists on the server, so the action can only be discarded.",
        ["sync.advice_permission"] = "Your permission for this ticket was revoked. Please contact an administrator.",
        ["sync.advice_status"] = "Someone else changed the status in the meantime. Forcing will overwrite that value.",
        ["sync.action_add_comment"] = "Add comment",
        ["sync.action_add_note"] = "Add note",
        ["sync.action_assign"] = "Assign ticket",
        ["sync.action_update_status"] = "Change status",
        ["sync.action_create"] = "Create new ticket",
        ["sync.action_clear_assignee"] = "Remove assignment",
        ["sync.action_update_fields"] = "Update ticket fields",
        ["sync.action_delete"] = "Delete ticket",
        ["sync.action_upload"] = "Upload attachment",

        // Team
        ["team.members"] = "Members",
        ["team.tickets_per_person"] = "Tickets/Person",
        ["team.tickets_30d"] = "Tickets (30d)",
        ["team.closed"] = "Closed",
        ["team.response_time"] = "Response time",
        ["team.overdue"] = "Overdue",
        ["team.most_requests"] = "Most requests",
        ["team.most_assignments"] = "Most assignments",
        ["team.workload"] = "Team workload",
        ["team.no_members"] = "No team members found.",
        ["team.assigned"] = "Assigned",
        ["team.open"] = "Open",
        ["team.workload_col"] = "Workload",
        ["team.workload_high"] = "High",
        ["team.workload_medium"] = "Medium",
        ["team.workload_normal"] = "Normal",

        // Notifications
        ["notifications.unread"] = "Unread",
        ["notifications.read"] = "Read",
        ["notifications.none"] = "No notifications.",
        ["notifications.default_title"] = "Notification",
        ["notifications.load_more"] = "Load more",

        // Reports
        ["reports.weekly_trend"] = "Ticket Trend (last 8 weeks)",
        ["reports.created"] = "Created",
        ["reports.closed"] = "Closed",
        ["reports.no_data"] = "No data available.",
        ["reports.resolution_times"] = "Resolution Times",
        ["reports.resolved"] = "Resolved Tickets",
        ["reports.average"] = "Average",
        ["reports.fastest"] = "Fastest",
        ["reports.slowest"] = "Slowest",
        ["reports.sla_compliance"] = "SLA Compliance",
        ["reports.sla_met"] = "Met",
        ["reports.sla_breached"] = "Breached",
        ["reports.sla_at_risk"] = "At Risk",
        ["reports.no_deadline"] = "No deadline",
        ["reports.priority_dist"] = "Priority Distribution",
        ["reports.top_assignees"] = "Top Assignees",
        ["reports.no_deadline_tickets"] = "No tickets with due date",

        // Accessibility
        ["a11y.toggle_menu"] = "Toggle menu",
        ["a11y.notifications"] = "Notifications",
        ["a11y.toggle_darkmode"] = "Toggle dark mode",
        ["a11y.logout"] = "Log out",
        ["a11y.main_navigation"] = "Main navigation",
    };
}
