namespace THWTicketApp.Web.Services;

public class LocalizationService
{
    private readonly LocalStorageService _localStorage;
    private string _currentLanguage = "de";
    private bool _initialized;

    public event Action? LanguageChanged;
    public string CurrentLanguage => _currentLanguage;

    public LocalizationService(LocalStorageService localStorage)
    {
        _localStorage = localStorage;
    }

    public async Task InitializeAsync()
    {
        if (_initialized) return;
        var lang = await _localStorage.GetItemAsync("settings_language");
        if (!string.IsNullOrEmpty(lang)) _currentLanguage = lang;
        _initialized = true;
    }

    public async Task SetLanguageAsync(string language)
    {
        _currentLanguage = language;
        await _localStorage.SetItemAsync("settings_language", language);
        LanguageChanged?.Invoke();
    }

    public string T(string key) => Get(key, _currentLanguage);

    private static string Get(string key, string lang)
    {
        if (lang == "en" && En.TryGetValue(key, out var en)) return en;
        if (De.TryGetValue(key, out var de)) return de;
        return key;
    }

    private static readonly Dictionary<string, string> De = new()
    {
        // Navigation
        ["nav.dashboard"] = "Dashboard",
        ["nav.tickets"] = "Tickets",
        ["nav.newticket"] = "Neues Ticket",
        ["nav.kanban"] = "Kanban Board",
        ["nav.team"] = "Team",
        ["nav.reports"] = "Berichte",
        ["nav.scanner"] = "Scanner",
        ["nav.notifications"] = "Benachrichtigungen",
        ["nav.syncconflicts"] = "Sync-Konflikte",
        ["nav.settings"] = "Einstellungen",
        ["nav.bugreports"] = "Bug-Reports",

        // Common
        ["common.save"] = "Speichern",
        ["common.cancel"] = "Abbrechen",
        ["common.delete"] = "Löschen",
        ["common.edit"] = "Bearbeiten",
        ["common.close"] = "Schließen",
        ["common.open"] = "Öffnen",
        ["common.print"] = "Drucken",
        ["common.popup_blocked"] = "Popup blockiert – bitte Popups für diese Seite erlauben",
        ["common.search"] = "Suchen",
        ["common.filter"] = "Filter",
        ["common.refresh"] = "Aktualisieren",
        ["common.loading"] = "Laden...",
        ["common.error"] = "Fehler",
        ["common.success"] = "Erfolgreich",
        ["common.all"] = "Alle",
        ["common.yes"] = "Ja",
        ["common.no"] = "Nein",
        ["common.back"] = "Zurück",
        ["common.logout"] = "Abmelden",
        ["common.clear"] = "Leeren",

        // Onboarding tour
        ["onboarding.step"] = "Schritt",
        ["onboarding.next"] = "Weiter",
        ["onboarding.skip"] = "Überspringen",
        ["onboarding.finish"] = "Los geht's!",
        ["onboarding.step1_title"] = "Willkommen bei der THW Ticket App",
        ["onboarding.step1_body"] = "In den nächsten Schritten zeigen wir dir die wichtigsten Funktionen. Dauert etwa eine Minute — überspringbar jederzeit oben rechts.",
        ["onboarding.step2_title"] = "Dashboard und Ticket-Liste",
        ["onboarding.step2_body"] = "Das Dashboard zeigt dir auf einen Blick Anzahl offener, in Bearbeitung und geschlossener Tickets. Klick auf eine Kachel filtert die Liste sofort. In der Ticket-Liste kannst du suchen, sortieren und nach Status/Priorität/Gruppe filtern.",
        ["onboarding.step3_title"] = "Neue Tickets erstellen",
        ["onboarding.step3_body"] = "Der blaue Plus-Button unten rechts öffnet das Formular von jeder Seite aus. Tipp: Was du tippst wird automatisch als Entwurf gespeichert — wenn der Browser abstürzt oder du den Tab schließt, geht nichts verloren.",
        ["onboarding.step4_title"] = "Ticket bearbeiten",
        ["onboarding.step4_body"] = "Auf der Detail-Seite: Klick auf den Titel oder die Beschreibung zum Bearbeiten. Die Status-/Prioritäts-/Gruppen-/Zuweisungs-Chips oben sind klickbar — ein Klick öffnet ein Menü, ein weiterer Klick wechselt den Wert. Kommentare und Notizen erscheinen chronologisch im Activity-Feed.",
        ["onboarding.step5_title"] = "Kanban-Board",
        ["onboarding.step5_body"] = "Im Kanban siehst du alle Tickets nach Status gruppiert. Am Desktop ziehst du Karten zwischen Spalten per Drag-and-Drop. Auf Mobile wechselst du Status über das ↔-Icon auf der Karte. Mit dem Filter „Meine Tickets“ siehst du nur deine.",
        ["onboarding.step6_title"] = "Schnell-Suche und Tastatur",
        ["onboarding.step6_body"] = "Drücke Strg+K (oder Cmd+K auf Mac) auf jeder Seite — die Befehlspalette öffnet sich. Tippe Ticket-Nummer oder Stichwort, oder navigiere zu jeder Seite. Mit „?“ siehst du alle Tastatur-Shortcuts, mit „/“ springst du direkt in die Suche der Ticket-Liste.",
        ["onboarding.step7_title"] = "Anmelden mit Passkey",
        ["onboarding.step7_body"] = "Unter Einstellungen → Passkey kannst du dein Gerät registrieren. Danach meldest du dich per Fingerabdruck, Gesichtserkennung oder Geräte-PIN an — kein Passwort mehr. Wenn du Auto-Lock aktivierst, sperrt sich die App nach Inaktivität automatisch.",
        ["onboarding.step8_title"] = "Noch mehr entdecken",
        ["onboarding.step8_body"] = "In den Einstellungen findest du Benachrichtigungen, Dark-Mode, Sprache, Theme-Farbe und mehr. Du kannst diese Einführung dort jederzeit über „Einführung erneut anzeigen“ wieder öffnen. Wenn du Fragen hast: dein OV-Admin hilft weiter.",
        ["settings.show_onboarding"] = "Einführung erneut anzeigen",
        ["settings.show_whatsnew"] = "Was ist neu?",
        ["whatsnew.title"] = "Was ist neu?",
        ["whatsnew.dismiss"] = "Alles klar",
        ["settings.autosave_hint"] = "Änderungen werden automatisch gespeichert.",
        ["settings.notifications_enable"] = "Benachrichtigungen aktivieren",
        ["settings.advanced"] = "Erweitert",
        ["settings.advanced_warning"] = "Diese Einstellungen sind nur für Administratoren — falsche Werte können die App unbenutzbar machen.",
        ["settings.danger_zone"] = "Konto",
        ["settings.logout_hint"] = "Beendet die Session auf diesem Gerät.",
        ["notifications.mark_all_read"] = "Alle als gelesen",
        ["notifications.mark_read"] = "Als gelesen markieren",
        ["notifications.mark_failed"] = "Konnte nicht als gelesen markiert werden.",
        ["notifications.marked_all"] = "{0} Benachrichtigungen als gelesen markiert.",

        // Login
        ["login.title"] = "Anmelden",
        ["login.username"] = "Benutzername",
        ["login.password"] = "Passwort",
        ["login.submit"] = "Anmelden",
        ["login.submitting"] = "Anmelden...",
        ["login.failed"] = "Anmeldung fehlgeschlagen. Bitte Benutzername und Passwort prüfen.",
        ["login.connection_error"] = "Verbindungsfehler",
        ["login.passkey"] = "Mit Passkey anmelden",
        ["login.passkey_failed"] = "Passkey-Anmeldung fehlgeschlagen.",
        ["login.passkey_cancelled"] = "Passkey-Anmeldung abgebrochen.",
        ["login.passkey_no_session"] = "Passkey OK, aber keine gesperrte Sitzung gefunden. Bitte einmal mit Benutzername und Passwort anmelden — danach funktioniert der Passkey-Button.",
        ["login.username_required"] = "Benutzername ist erforderlich",
        ["login.password_required"] = "Passwort ist erforderlich",

        // Tickets
        ["tickets.title"] = "Tickets",
        ["tickets.new"] = "Neues Ticket",
        ["tickets.search"] = "Tickets suchen...",
        ["tickets.active"] = "Aktiv",
        ["tickets.open"] = "Offen",
        ["tickets.pending"] = "In Bearbeitung",
        ["tickets.closed"] = "Geschlossen",
        ["tickets.mytickets"] = "Meine Tickets",
        ["tickets.sort"] = "Sortierung",
        ["tickets.sort.newest"] = "Erstellt (neueste)",
        ["tickets.sort.oldest"] = "Erstellt (älteste)",
        ["tickets.sort.updated"] = "Zuletzt aktualisiert",
        ["tickets.sort.priority"] = "Priorität",
        ["tickets.sort.subject"] = "Betreff (A-Z)",
        ["tickets.none"] = "Keine Tickets gefunden.",
        ["tickets.empty_description"] = "Erstelle das erste Ticket — oder ändere deine Filter, falls hier eigentlich welche sein sollten.",
        ["tickets.assigned"] = "Ticket zugewiesen.",
        ["tickets.closed_success"] = "Ticket geschlossen.",
        ["tickets.savefilter"] = "Filter speichern",
        ["tickets.loadfilter"] = "Gespeicherte Filter",
        ["tickets.deletefilter"] = "Filter löschen",
        ["tickets.filtername"] = "Filtername",

        // Markdown editor toolbar
        ["editor.toolbar"] = "Textformatierung",
        ["editor.bold"] = "Fett",
        ["editor.italic"] = "Kursiv",
        ["editor.underline"] = "Unterstrichen",
        ["editor.strike"] = "Durchgestrichen",
        ["editor.code"] = "Code",
        ["editor.list"] = "Liste",
        ["editor.bold_placeholder"] = "fetter Text",
        ["editor.italic_placeholder"] = "kursiver Text",
        ["editor.underline_placeholder"] = "unterstrichener Text",
        ["editor.strike_placeholder"] = "durchgestrichener Text",
        ["editor.code_placeholder"] = "Code",
        ["editor.list_placeholder"] = "Listenpunkt",

        // Ticket Detail
        ["detail.description"] = "Beschreibung",
        ["detail.no_description"] = "Keine Beschreibung.",
        ["detail.edit"] = "Ticket bearbeiten",
        ["detail.subject"] = "Betreff",
        ["detail.status"] = "Status",
        ["detail.priority"] = "Priorität",
        ["detail.creator"] = "Ersteller",
        ["detail.assignee"] = "Zuständig",
        ["detail.unassigned"] = "Nicht zugewiesen",
        ["detail.group"] = "Gruppe",
        ["detail.type"] = "Typ",
        ["detail.created"] = "Erstellt",
        ["detail.updated"] = "Aktualisiert",
        ["detail.due"] = "Fällig",
        ["detail.no_due"] = "Kein Datum",
        ["detail.assign_to"] = "Zuweisen an",
        ["detail.assign"] = "Zuweisen",
        ["detail.remove_assign"] = "Entfernen",
        ["detail.tags"] = "Tags",
        ["detail.linked"] = "Verknüpfte Tickets",
        ["detail.no_links"] = "Keine Verknüpfungen.",
        ["detail.link_related"] = "Verwandt",
        ["detail.link_blocks"] = "Blockiert",
        ["detail.link_blocked_by"] = "Blockiert von",
        ["detail.link_duplicate"] = "Duplikat",
        ["detail.subscribe"] = "Abonnieren",
        ["detail.unsubscribe"] = "Abbestellen",
        ["detail.subscribed"] = "Ticket abonniert.",
        ["detail.unsubscribed"] = "Abo entfernt.",
        ["detail.delete_ticket"] = "Ticket löschen",
        ["detail.not_found"] = "Ticket nicht gefunden.",

        // Comments & Notes
        ["comments.title"] = "Kommentare",
        ["comments.new"] = "Neuer Kommentar",
        ["comments.send"] = "Kommentar senden",
        ["comments.added"] = "Kommentar hinzugefügt.",
        ["comments.preview_toggle"] = "Markdown-Vorschau umschalten",
        ["comments.preview_on"] = "Vorschau",
        ["comments.preview_off"] = "Bearbeiten",
        ["comments.preview_empty"] = "Tippe etwas ein, um die Vorschau zu sehen.",
        ["attachments.drop_hint"] = "oder Dateien hier reinziehen",
        ["comments.quickreply"] = "Schnellantwort einfügen",
        ["comments.mention"] = "Erwähnen",
        ["notes.title"] = "Notizen",
        ["notes.new"] = "Neue Notiz",
        ["notes.add"] = "Notiz hinzufügen",
        ["notes.added"] = "Notiz hinzugefügt.",
        ["offline.queued"] = "Offline gespeichert — wird gesendet, sobald die Verbindung wieder steht.",
        ["offline.action_unavailable"] = "Diese Aktion benötigt eine Online-Verbindung.",

        // Attachments
        ["attachments.title"] = "Anhänge",
        ["attachments.none"] = "Keine Anhänge.",
        ["attachments.upload"] = "Datei hochladen",
        ["attachments.take_photo"] = "Foto aufnehmen",
        ["attachments.uploading"] = "Wird hochgeladen...",
        ["attachments.uploaded"] = "Datei hochgeladen.",
        ["attachments.deleted"] = "Anhang gelöscht.",
        ["attachments.dsgvo_hint"] = "Bitte keine Personen ohne Einwilligung fotografieren. Bilder werden serverseitig auf max. 2400 px komprimiert.",
        ["attachments.name"] = "Name",
        ["attachments.type"] = "Typ",
        ["attachments.size"] = "Größe",
        ["attachments.date"] = "Datum",
        ["attachments.actions"] = "Aktionen",

        // Time Tracking
        ["time.title"] = "Zeiterfassung",
        ["time.timer"] = "Timer",
        ["time.start"] = "Starten",
        ["time.stop"] = "Stoppen",
        ["time.description"] = "Beschreibung (optional)",
        ["time.total"] = "Gesamt",
        ["time.no_entries"] = "Keine Zeiteinträge.",
        ["time.col_start"] = "Start",
        ["time.col_duration"] = "Dauer",
        ["time.col_description"] = "Beschreibung",

        // History
        ["history.title"] = "Verlauf",

        // Assets
        ["nav.assets"] = "Ausstattung",
        ["assets.new"] = "Neues Asset",
        ["assets.name"] = "Name",
        ["assets.tag"] = "Asset-Tag",
        ["assets.category"] = "Kategorie",
        ["assets.location"] = "Standort",
        ["assets.none"] = "Keine Assets vorhanden.",
        ["assets.name_required"] = "Name ist erforderlich.",
        ["assets.delete_confirm"] = "Asset wirklich löschen?",
        ["assets.link_ticket"] = "Mit Ticket verknüpfen",
        ["assets.link_ticket_prompt"] = "Ticket-Nummer",
        ["assets.link_ticket_empty"] = "Bitte Ticket-Nummer eingeben.",
        ["assets.link_ticket_success"] = "Asset mit Ticket verknüpft.",
        ["assets.link_ticket_failed"] = "Verknüpfung fehlgeschlagen.",

        // Templates
        ["nav.templates"] = "Ticket-Vorlagen",
        ["templates.new"] = "Neue Vorlage",
        ["templates.none"] = "Keine Vorlagen vorhanden.",
        ["templates.empty_description"] = "Lege Vorlagen an, um wiederkehrende Tickets schneller zu erstellen.",
        ["templates.name"] = "Name",
        ["templates.subject"] = "Betreff",
        ["templates.issue"] = "Beschreibung",
        ["templates.issue_preview"] = "Beschreibung",
        ["templates.name_required"] = "Name ist erforderlich.",
        ["templates.subject_required"] = "Betreff ist erforderlich.",
        ["templates.delete_confirm"] = "Vorlage wirklich löschen?",
        ["templates.checklist"] = "Checkliste",
        ["templates.checklist_add"] = "Punkt hinzufügen",
        ["templates.checklist_hint"] = "Wird beim Anwenden der Vorlage als Ticket-Checkliste übernommen",

        // Calendar
        ["nav.calendar"] = "Kalender",
        ["calendar.from"] = "Von",
        ["calendar.to"] = "Bis",
        ["calendar.load"] = "Laden",
        ["calendar.this_month"] = "Aktueller Monat",
        ["calendar.none"] = "Keine Ereignisse im gewählten Zeitraum.",
        ["calendar.empty_description"] = "Termine aus Tickets mit Fälligkeitsdatum erscheinen hier automatisch.",
        ["calendar.range_required"] = "Bitte Start- und Enddatum wählen.",
        ["calendar.range_invalid"] = "Das Enddatum muss nach dem Startdatum liegen.",
        ["calendar.ticket_deadline"] = "Ticket-Frist",
        ["calendar.recurring_task"] = "Wiederkehrende Aufgabe",
        ["calendar.open_ticket"] = "Ticket öffnen",

        // Recurring Tasks
        ["nav.recurring"] = "Wiederkehrende Aufgaben",
        ["recurring.new"] = "Neue Aufgabe",
        ["recurring.active"] = "Aktiv",
        ["recurring.inactive"] = "Inaktiv",
        ["recurring.schedule"] = "Zeitplan",
        ["recurring.ticket_subject"] = "Ticket-Betreff",
        ["recurring.ticket_template"] = "Ticket-Vorlage",
        ["recurring.schedule_type"] = "Wiederholungsart",
        ["recurring.monthly"] = "Monatlich",
        ["recurring.quarterly"] = "Quartalsweise",
        ["recurring.annual"] = "Jährlich",
        ["recurring.day_of_month"] = "Tag im Monat",
        ["recurring.days_before"] = "Tage vor Fälligkeit",
        ["recurring.enabled"] = "Aktiviert",
        ["recurring.next_run"] = "Nächste Ausführung",
        ["recurring.none"] = "Keine wiederkehrenden Aufgaben.",
        ["recurring.name_required"] = "Name ist erforderlich.",
        ["recurring.refs_required"] = "Bitte Typ, Priorität und Gruppe wählen.",
        ["recurring.delete_confirm"] = "Aufgabe wirklich löschen?",

        // Reports
        ["reports.handover"] = "Übergabebericht",
        ["reports.sitzung"] = "OV-Sitzungsbericht",
        ["reports.generate"] = "Bericht erstellen",
        ["reports.copy"] = "In Zwischenablage kopieren",
        ["reports.copied"] = "Bericht kopiert.",
        ["reports.copy_failed"] = "Kopieren fehlgeschlagen.",
        ["reports.download_md"] = "Als Markdown herunterladen",
        ["reports.print"] = "Drucken / Als PDF speichern",

        // Settings
        ["settings.title"] = "Einstellungen",
        ["settings.appearance"] = "Erscheinungsbild",
        ["settings.darkmode"] = "Dark Mode",
        ["settings.notifications"] = "Benachrichtigungen",
        ["settings.notifications_desc"] = "Über neue Tickets und Änderungen informieren",
        ["settings.notify_new"] = "Neue Tickets",
        ["settings.notify_comments"] = "Kommentare",
        ["settings.notify_status"] = "Statusänderungen",
        ["settings.notify_mine"] = "Nur meine Tickets",
        ["settings.notify_mine_desc"] = "Nur bei mir zugewiesenen Tickets",
        ["settings.notify_highprio"] = "Nur hohe Priorität",
        ["settings.notify_highprio_desc"] = "Nur bei hoher/dringender Priorität",
        ["settings.language"] = "Sprache / Language",
        ["settings.api"] = "API-Konfiguration",
        ["settings.api_url"] = "Server-URL",
        ["settings.timeout"] = "Verbindungs-Timeout (Sekunden)",
        ["settings.test_connection"] = "Verbindung testen",
        ["settings.testing"] = "Teste...",
        ["settings.cache"] = "Offline-Cache",
        ["settings.cache_enable"] = "Offline-Caching aktivieren",
        ["settings.cache_desc"] = "Tickets lokal speichern für Offline-Zugriff",
        ["settings.cache_clear"] = "Cache leeren",
        ["settings.saved"] = "Einstellungen gespeichert.",
        ["settings.passkey"] = "Passkey / Biometrie",
        ["settings.passkey_register"] = "Passkey registrieren",
        ["settings.passkey_registered"] = "Passkey registriert",
        ["settings.passkey_remove"] = "Passkey entfernen",
        ["settings.passkey_desc"] = "Schnelle Anmeldung per Fingerabdruck, Gesicht oder Geräte-PIN",
        ["settings.passkey_not_supported"] = "Ihr Browser unterstützt keine Passkeys.",
        ["settings.passkey_register_failed"] = "Passkey-Registrierung fehlgeschlagen.",
        ["settings.passkey_removed"] = "Passkey entfernt.",
        ["settings.idlelock"] = "Automatisch sperren",
        ["settings.idlelock_desc"] = "App nach Inaktivität sperren. Entsperren per Passkey/Biometrie. Erfordert registrierten Passkey.",
        ["settings.idlelock_enable"] = "Auto-Lock aktivieren",
        ["settings.idlelock_timeout"] = "Sperren nach",
        ["settings.idlelock_needs_passkey"] = "Ein Passkey muss registriert sein, damit Auto-Lock funktioniert.",
        ["idlelock.locked"] = "App gesperrt nach Inaktivität.",
        ["settings.timeout_invalid"] = "Timeout muss zwischen 5 und 300 Sekunden liegen.",
        ["settings.connection_testing"] = "Teste Verbindung...",
        ["settings.connection_success"] = "Verbindung erfolgreich!",
        ["settings.connection_timeout"] = "Zeitüberschreitung. Server antwortet nicht.",
        ["settings.connection_failed"] = "Verbindung fehlgeschlagen. Server nicht erreichbar.",
        ["settings.cache_cleared"] = "Cache geleert.",
        ["settings.theme_color"] = "Akzentfarbe",
        ["settings.about"] = "Über",
        ["settings.sync"] = "Sync-Konflikte",
        ["settings.sync_resolve"] = "Konflikte verwalten",
        ["settings.push_enable"] = "Push-Benachrichtigungen",
        ["settings.push_desc"] = "Liefert Benachrichtigungen auch wenn die App geschlossen ist.",
        ["settings.push_enable_failed"] = "Push konnte nicht aktiviert werden (Berechtigung verweigert oder Server nicht erreichbar).",
        ["settings.push_disable_failed"] = "Push konnte nicht deaktiviert werden.",
        ["bugreport.fab"] = "Bug melden",
        ["bugreport.title"] = "Fehler melden",
        ["bugreport.intro"] = "Beschreib kurz was nicht funktioniert. Beim Absenden werden automatisch Build-Version, aktuelle Seite und die letzten Browser-Konsolen-Meldungen mit übertragen.",
        ["bugreport.field_title"] = "Kurze Zusammenfassung",
        ["bugreport.field_description"] = "Was ist passiert? Wie kann man das reproduzieren?",
        ["bugreport.context_hint"] = "Technischer Kontext (Build, URL, User-Agent, Konsolen-Tail) wird automatisch angehängt.",
        ["bugreport.submit"] = "Absenden",
        ["bugreport.sent"] = "Bug-Report verschickt — Admins werden benachrichtigt.",
        ["bugreport.failed"] = "Senden fehlgeschlagen. Probier's später nochmal.",
        ["bugreport.admin_title"] = "Bug-Reports",
        ["bugreport.empty"] = "Keine Bug-Reports.",
        ["bugreport.count"] = "{0} offen / {1} insgesamt",
        ["bugreport.from"] = "Von:",
        ["bugreport.context"] = "Technischer Kontext",
        ["bugreport.resolved"] = "Erledigt",
        ["bugreport.mark_resolved"] = "Als erledigt markieren",
        ["bugreport.reopen"] = "Wieder öffnen",
        ["bugreport.resolved_ok"] = "Als erledigt markiert.",
        ["bugreport.reopened_ok"] = "Wieder geöffnet.",
        ["bugreport.deleted"] = "Bug-Report gelöscht.",
        ["settings.update_check"] = "Nach Updates suchen",
        ["settings.update_checking"] = "Wird geprüft...",
        ["settings.update_uptodate"] = "Bereits aktuell.",
        ["settings.update_failed"] = "Update-Prüfung fehlgeschlagen.",
        ["settings.synclog"] = "Sync-Log",
        ["settings.synclog_desc"] = "Protokoll der Offline-Synchronisierung",
        ["settings.synclog_empty"] = "Keine Log-Einträge vorhanden.",
        ["settings.synclog_export"] = "Log exportieren",
        ["settings.synclog_clear"] = "Log leeren",
        ["settings.synclog_cleared"] = "Sync-Log geleert.",
        ["settings.synclog_time"] = "Zeitpunkt",
        ["settings.synclog_level"] = "Stufe",
        ["settings.synclog_action"] = "Aktion",
        ["settings.synclog_message"] = "Nachricht",

        // Batch
        ["batch.toggle"] = "Mehrfachauswahl",
        ["batch.selected"] = "{0} Ticket(s) ausgewählt",
        ["batch.empty"] = "Keine Tickets ausgewählt",
        ["batch.select_all_visible"] = "Alle auf dieser Seite",
        ["batch.change_status"] = "Status ändern",
        ["batch.deleted"] = "{0} gelöscht, {1} fehlgeschlagen",
        ["batch.updated"] = "{0} aktualisiert, {1} fehlgeschlagen",
        ["batch.status_changed"] = "{0} auf „{1}“ geändert, {2} fehlgeschlagen",
        ["tickets.change_status"] = "Status ändern…",
        ["tickets.status_changed"] = "Status auf „{0}“ geändert.",
        ["detail.print"] = "Drucken / Als PDF speichern",
        ["detail.show_qr"] = "QR-Code anzeigen",
        ["detail.print_qr"] = "QR-Code drucken",

        // Profile
        ["nav.profile"] = "Profil",
        ["profile.title"] = "Profil",
        ["profile.info"] = "Persönliche Daten",
        ["profile.fullname"] = "Vollständiger Name",
        ["profile.job_title"] = "Funktion",
        ["profile.work_number"] = "Dienstliche Telefonnummer",
        ["profile.mobile_number"] = "Mobilnummer",
        ["profile.username"] = "Benutzername",
        ["profile.email"] = "E-Mail-Adresse",
        ["profile.saved"] = "Profil gespeichert.",
        ["profile.load_failed"] = "Profil konnte nicht geladen werden. Bitte später erneut versuchen.",
        ["profile.avatar_pick"] = "Profilbild ändern",
        ["profile.avatar_uploading"] = "Wird hochgeladen…",
        ["profile.avatar_saved"] = "Profilbild aktualisiert.",
        ["profile.avatar_failed"] = "Profilbild konnte nicht hochgeladen werden.",
        ["profile.avatar_too_large"] = "Bild ist zu groß (max. 5 MB).",
        ["profile.avatar_offline"] = "Profilbild kann nur online geändert werden.",
        ["profile.change_password"] = "Passwort ändern",
        ["profile.current_password"] = "Aktuelles Passwort",
        ["profile.new_password"] = "Neues Passwort",
        ["profile.confirm_password"] = "Passwort bestätigen",
        ["profile.update_password"] = "Passwort ändern",
        ["profile.password_changed"] = "Passwort geändert.",
        ["profile.password_required"] = "Bitte alle Passwortfelder ausfüllen.",
        ["profile.password_mismatch"] = "Die Passwörter stimmen nicht überein.",
        ["profile.password_too_short"] = "Das Passwort muss mindestens 6 Zeichen haben.",
        ["profile.password_failed"] = "Passwortänderung fehlgeschlagen.",
        ["profile.sessions_title"] = "Aktive Sitzungen",
        ["profile.sessions_subtitle"] = "Geräte, die aktuell mit deinem Konto angemeldet sind.",
        ["profile.sessions_empty"] = "Keine aktiven Sitzungen gefunden.",
        ["profile.sessions_current"] = "Dieses Gerät",
        ["profile.sessions_legacy"] = "Alt",
        ["profile.sessions_legacy_label"] = "Alter Token (vor Multi-Device)",
        ["profile.sessions_unknown_device"] = "Unbekanntes Gerät",
        ["profile.sessions_last_seen"] = "Zuletzt",
        ["profile.sessions_created"] = "Erstellt",
        ["profile.sessions_revoke"] = "Abmelden",
        ["profile.sessions_revoke_title"] = "Gerät abmelden?",
        ["profile.sessions_revoke_confirm"] = "Dieses Gerät wird sofort von deinem Konto abgemeldet.",
        ["profile.sessions_revoke_others"] = "Alle anderen Geräte abmelden",
        ["profile.sessions_revoke_others_title"] = "Alle anderen Geräte abmelden?",
        ["profile.sessions_revoke_others_confirm"] = "Alle anderen Sitzungen werden sofort beendet. Dieses Gerät bleibt angemeldet.",
        ["profile.sessions_revoked"] = "Sitzung beendet.",
        ["profile.sessions_revoke_failed"] = "Abmelden fehlgeschlagen.",
        ["profile.my_data_title"] = "Meine Daten",
        ["profile.my_data_subtitle"] = "Auskunft über deine gespeicherten Daten (Art. 15 DSGVO).",
        ["profile.export_data"] = "Meine Daten exportieren (DSGVO)",
        ["profile.export_failed"] = "Export fehlgeschlagen. Bitte später erneut versuchen.",
        ["profile.export_offline"] = "Der Datenexport ist offline nicht verfügbar.",

        // PWA
        ["pwa.install_hint"] = "App zum Startbildschirm hinzufügen für schnelleren Zugriff.",
        ["pwa.install"] = "Installieren",

        // Notifications (browser)
        ["notify.ticket_created"] = "Neues Ticket",
        ["notify.ticket_created_body"] = "Ticket #{0} wurde erstellt.",
        ["notify.ticket_updated"] = "Ticket aktualisiert",
        ["notify.ticket_updated_body"] = "Ticket #{0} wurde geändert.",
        ["notify.status_changed"] = "Status geändert",
        ["notify.status_changed_body"] = "Status von Ticket #{0} wurde geändert.",
        ["notify.assignee_changed"] = "Zuweisung geändert",
        ["notify.assignee_changed_body"] = "Zuweisung von Ticket #{0} wurde geändert.",
        ["notify.comment_added"] = "Neuer Kommentar",
        ["notify.comment_added_body"] = "Neuer Kommentar bei Ticket #{0}.",
        ["notify.ticket_event"] = "Ticket-Ereignis",
        ["notify.ticket_event_body"] = "Änderung bei Ticket #{0}.",

        // Kanban
        ["kanban.board"] = "Kanban-Board",
        ["kanban.tickets"] = "Tickets",
        ["kanban.ticket_moved"] = "Ticket verschoben",
        ["kanban.move_failed"] = "Status-Änderung fehlgeschlagen.",
        ["kanban.status_not_allowed"] = "Status \"{0}\" ist für Typ \"{1}\" nicht erlaubt.",
        ["kanban.move_to"] = "Status ändern",
        ["kanban.column_empty"] = "Keine Tickets in dieser Spalte.",
        ["kanban.no_subject"] = "(Kein Betreff)",
        ["common.unknown"] = "Unbekannt",
        ["common.or"] = "oder",
        ["common.network_error"] = "Netzwerkfehler. Bitte erneut versuchen.",

        // Ticket Detail (additional)
        ["detail.details"] = "Details",
        ["detail.activity"] = "Aktivität",
        ["detail.activity_comments_notes"] = "Kommentare & Notizen",
        ["detail.activity_history"] = "Verlauf",
        ["detail.activity_empty"] = "Noch keine Aktivität. Schreib unten den ersten Kommentar oder eine Notiz.",
        ["detail.activity_internal"] = "Intern",
        ["detail.click_to_edit"] = "Klicken zum Bearbeiten",
        ["detail.composer_comment"] = "Kommentar",
        ["detail.composer_note"] = "Notiz",
        ["detail.composer_open"] = "Kommentar oder Notiz schreiben",
        ["detail.composer_close"] = "Schließen",
        ["detail.note_visible_internal"] = "Notizen sind nur für Agents sichtbar, nicht für den Ticket-Ersteller.",
        ["detail.no_group"] = "Keine Gruppe",
        ["detail.no_assignees_available"] = "Keine Zuweisbaren — möglicherweise fehlende Berechtigung.",
        ["detail.favorite"] = "Favorit",
        ["time.entries_short"] = "Einträge",
        ["detail.ticket_updated"] = "Ticket aktualisiert.",
        ["detail.update_failed"] = "Aktualisierung fehlgeschlagen.",
        ["detail.assign_updated"] = "Zuweisung aktualisiert.",
        ["detail.assign_failed"] = "Zuweisung fehlgeschlagen.",
        ["detail.assign_removed"] = "Zuweisung entfernt.",
        ["detail.additional_assignees"] = "Weitere Zuständige",
        ["detail.additional_assignees_add"] = "Person hinzufügen",
        ["detail.add_failed"] = "Fehler beim Hinzufügen.",
        ["detail.delete_failed"] = "Löschen fehlgeschlagen.",
        ["detail.ticket_deleted"] = "Ticket gelöscht.",
        ["detail.templates_saved"] = "Vorlagen gespeichert.",
        ["detail.edit_templates"] = "Vorlagen bearbeiten",
        ["detail.quickreply_templates"] = "Schnellantwort-Vorlagen",
        ["detail.new_template"] = "Neu",
        ["detail.link_ticket_num"] = "Ticket #",
        ["common.add"] = "Hinzufügen",

        // Checklist
        ["checklist.title"] = "Checkliste",
        ["checklist.empty"] = "Keine Einträge.",
        ["checklist.new_item"] = "Neuer Eintrag",

        ["detail.add_tag"] = "Tag hinzufügen",
        ["detail.tag_added"] = "Tag hinzugefügt",
        ["detail.tag_removed"] = "Tag entfernt.",

        // Tickets (additional)
        ["tickets.assign_me"] = "Mir zuweisen",
        ["tickets.actions"] = "Ticket-Aktionen",
        ["tickets.assign_failed"] = "Zuweisung fehlgeschlagen.",
        ["tickets.close_failed"] = "Schließen fehlgeschlagen.",
        ["tickets.filter_saved"] = "Filter gespeichert.",
        ["tickets.filter_deleted"] = "Filter gelöscht.",
        ["tickets.create_title"] = "Neues Ticket erstellen",
        ["tickets.subject_required"] = "Betreff ist erforderlich",
        ["tickets.description_required"] = "Beschreibung ist erforderlich",
        ["tickets.group_required"] = "Gruppe ist erforderlich",
        ["tickets.create"] = "Ticket erstellen",
        ["tickets.export_csv"] = "Als CSV exportieren",
        ["tickets.use_template"] = "Vorlage verwenden",
        ["tickets.form_load_error"] = "Fehler beim Laden der Formulardaten.",
        ["tickets.no_visible_groups"] = "Du bist keiner Gruppe zugeordnet — bitte einen Admin kontaktieren.",
        ["tickets.created"] = "Ticket erstellt!",
        ["tickets.server_rejected"] = "Server hat das Ticket abgelehnt.",
        ["tickets.draft_restored"] = "Entwurf wiederhergestellt — du kannst da weitermachen, wo du aufgehört hast.",
        ["tickets.draft_discard"] = "Verwerfen",
        ["tickets.attachments_label"] = "Anhänge (optional)",
        ["tickets.attachments_pick"] = "Dateien auswählen",
        ["tickets.attachments_selected"] = "{0} Datei(en) ausgewählt",
        ["tickets.attachments_remove"] = "Entfernen",
        ["tickets.attachments_too_large"] = "{0} ist zu groß (max. 25 MB).",
        ["tickets.attachments_uploading"] = "Lade Anhänge hoch…",
        ["tickets.attachments_partial"] = "Ticket erstellt, aber {0} von {1} Anhängen konnten nicht hochgeladen werden.",
        ["tickets.attachments_offline"] = "Offline — {0} Anhang/Anhänge konnten nicht übernommen werden. Bitte später im Ticket hinzufügen.",
        ["tickets.template_checklist_info"] = "{0} Checklisten-Punkte werden übernommen",

        // Dashboard
        ["dashboard.total"] = "Gesamt",
        ["dashboard.open"] = "Offen",
        ["dashboard.in_progress"] = "In Bearbeitung",
        ["dashboard.closed"] = "Geschlossen",
        ["dashboard.mine"] = "Meine",
        ["dashboard.overdue"] = "Überfällig",
        ["dashboard.recent"] = "Letzte Tickets",
        ["dashboard.view_all"] = "Alle anzeigen",
        ["dashboard.no_tickets"] = "Keine Tickets vorhanden.",
        ["dashboard.quick_actions"] = "Schnellaktionen",
        ["dashboard.tickets_per_group"] = "Tickets pro Gruppe",
        ["dashboard.open_suffix"] = "offen",
        ["dashboard.welcome"] = "Willkommen!",
        ["dashboard.welcome_user"] = "Willkommen",
        ["dashboard.recently_visited"] = "Zuletzt besucht",
        ["time.just_now"] = "gerade eben",
        ["time.minutes_ago"] = "Min. her",
        ["time.hours_ago"] = "Std. her",
        ["time.days_ago"] = "Tage her",
        ["dashboard.beschluesse"] = "Offene Beschlüsse",
        ["dashboard.upcoming_tasks"] = "Nächste Aufgaben",
        ["dashboard.assets_total"] = "Assets gesamt",

        // Login (additional)
        ["login.configure_server"] = "Bitte zuerst die Server-URL konfigurieren.",
        ["login.server_config"] = "Server-Konfiguration",
        ["login.server_url"] = "Server-URL",
        ["login.save_url"] = "URL speichern",
        ["login.invalid_url"] = "Bitte eine gültige Server-URL eingeben.",
        ["login.passkey_cancelled"] = "Passkey-Anmeldung abgebrochen.",
        ["login.register_link"] = "Noch kein Konto? Jetzt registrieren",

        // Registration
        ["register.title"] = "Konto erstellen",
        ["register.fullname"] = "Vor- und Nachname",
        ["register.fullname_required"] = "Name ist erforderlich (mindestens 5 Zeichen)",
        ["register.username"] = "Benutzername",
        ["register.username_required"] = "Benutzername ist erforderlich (3–50 Zeichen)",
        ["register.username_hint"] = "3–50 Zeichen: Buchstaben, Zahlen, Punkt, Bindestrich, Unterstrich",
        ["register.email"] = "E-Mail-Adresse",
        ["register.email_required"] = "E-Mail ist erforderlich",
        ["register.password"] = "Passwort",
        ["register.password_required"] = "Passwort ist erforderlich",
        ["register.password_hint"] = "Mindestens 8 Zeichen, davon 3 verschiedene Arten: Klein-/Großbuchstaben, Zahlen, Sonderzeichen",
        ["register.password_confirm"] = "Passwort bestätigen",
        ["register.password_mismatch"] = "Passwörter stimmen nicht überein",
        ["register.captcha"] = "Sicherheitscode",
        ["register.captcha_required"] = "Sicherheitscode ist erforderlich",
        ["register.captcha_hint"] = "Bitte den Code aus dem Bild abtippen (Groß-/Kleinschreibung beachten)",
        ["register.captcha_refresh"] = "Neuen Code laden",
        ["register.captcha_error"] = "Sicherheitscode konnte nicht geladen werden",
        ["register.submit"] = "Konto erstellen",
        ["register.submitting"] = "Wird erstellt...",
        ["register.success"] = "Konto erfolgreich erstellt! Du kannst dich jetzt anmelden.",
        ["register.failed"] = "Registrierung fehlgeschlagen",
        ["register.email_exists"] = "Diese E-Mail-Adresse wird bereits verwendet.",
        ["register.username_exists"] = "Dieser Benutzername ist bereits vergeben.",
        ["register.disabled"] = "Die Registrierung ist derzeit deaktiviert.",
        ["register.login_link"] = "Bereits ein Konto? Zur Anmeldung",
        ["register.invalid_captcha"] = "Sicherheitscode falsch. Bitte erneut versuchen.",

        // Scanner
        ["scanner.instruction"] = "Scannen Sie einen QR-Code oder Barcode, um ein Ticket zu öffnen.",
        ["scanner.not_supported"] = "Ihr Browser unterstützt die BarcodeDetector API nicht. Bitte geben Sie die Ticket-Nummer manuell ein.",
        ["scanner.start_camera"] = "Kamera starten",
        ["scanner.stop_camera"] = "Kamera stoppen",
        ["scanner.manual_input"] = "Manuelle Eingabe",
        ["scanner.ticket_number"] = "Ticket-Nummer",
        ["scanner.open_ticket"] = "Öffnen",
        ["scanner.camera_failed"] = "Kamera konnte nicht gestartet werden.",
        ["scanner.detected"] = "Erkannt",

        // Sync Conflicts
        ["sync.no_conflicts"] = "Keine Sync-Konflikte vorhanden.",
        ["sync.conflicts_found"] = "{0} Konflikte gefunden. Bitte entscheiden Sie für jede Aktion, ob sie trotzdem angewendet oder verworfen werden soll.",
        ["sync.force_apply"] = "Trotzdem anwenden",
        ["sync.discard"] = "Verwerfen",
        ["sync.applied"] = "Aktion erfolgreich angewendet.",
        ["sync.apply_failed"] = "Aktion konnte nicht angewendet werden.",
        ["sync.discarded"] = "Aktion verworfen.",
        ["sync.type_deleted"] = "Ticket gelöscht",
        ["sync.type_permission"] = "Keine Berechtigung",
        ["sync.type_status"] = "Status bereits geändert",
        ["sync.type_updated"] = "Ticket bearbeitet",
        ["sync.type_conflict"] = "Konflikt",
        ["sync.advice_deleted"] = "Da das Ticket serverseitig nicht mehr existiert, kann die Aktion nur verworfen werden.",
        ["sync.advice_permission"] = "Deine Berechtigung für dieses Ticket wurde entzogen. Bitte wende dich an einen Administrator.",
        ["sync.advice_status"] = "Jemand anderes hat den Status in der Zwischenzeit gesetzt. Erzwingen überschreibt diesen Wert.",
        ["sync.action_add_comment"] = "Kommentar hinzufügen",
        ["sync.action_add_note"] = "Notiz hinzufügen",
        ["sync.action_assign"] = "Ticket zuweisen",
        ["sync.action_update_status"] = "Status ändern",
        ["sync.action_create"] = "Neues Ticket erstellen",
        ["sync.action_clear_assignee"] = "Zuweisung entfernen",
        ["sync.action_set_additional_assignees"] = "Weitere Zuständige ändern",
        ["sync.action_update_fields"] = "Ticket-Felder aktualisieren",
        ["sync.action_delete"] = "Ticket löschen",
        ["sync.action_upload"] = "Anhang hochladen",

        // Team
        ["team.members"] = "Mitglieder",
        ["team.tickets_per_person"] = "Tickets/Person",
        ["team.tickets_30d"] = "Tickets (30T)",
        ["team.closed"] = "Geschlossen",
        ["team.response_time"] = "Antwortzeit",
        ["team.overdue"] = "Überfällig",
        ["team.most_requests"] = "Meiste Anfragen",
        ["team.most_assignments"] = "Meiste Zuweisungen",
        ["team.workload"] = "Teamauslastung",
        ["team.no_members"] = "Keine Teammitglieder gefunden.",
        ["team.assigned"] = "Zugewiesen",
        ["team.open"] = "Offen",
        ["team.workload_col"] = "Auslastung",
        ["team.workload_high"] = "Hoch",
        ["team.workload_medium"] = "Mittel",
        ["team.workload_normal"] = "Normal",

        // Notifications
        ["notifications.unread"] = "Ungelesen",
        ["notifications.read"] = "Gelesen",
        ["notifications.none"] = "Keine Benachrichtigungen vorhanden.",
        ["notifications.default_title"] = "Benachrichtigung",
        ["notifications.load_more"] = "Mehr laden",

        // Reports
        ["reports.weekly_trend"] = "Ticket-Trend (letzte 8 Wochen)",
        ["reports.created"] = "Erstellt",
        ["reports.closed"] = "Geschlossen",
        ["reports.no_data"] = "Keine Daten vorhanden.",
        ["reports.resolution_times"] = "Auflösungszeiten",
        ["reports.resolved"] = "Gelöste Tickets",
        ["reports.average"] = "Durchschnitt",
        ["reports.fastest"] = "Schnellste",
        ["reports.slowest"] = "Langsamste",
        ["reports.sla_compliance"] = "SLA-Einhaltung",
        ["reports.sla_met"] = "Eingehalten",
        ["reports.sla_breached"] = "Überschritten",
        ["reports.sla_at_risk"] = "Gefährdet",
        ["reports.no_deadline"] = "Ohne Frist",
        ["reports.priority_dist"] = "Prioritätsverteilung",
        ["reports.top_assignees"] = "Top Bearbeiter",
        ["reports.no_deadline_tickets"] = "Keine Tickets mit Fälligkeitsdatum",

        // Keyboard Shortcuts
        ["shortcuts.title"] = "Tastaturkürzel",
        ["shortcuts.new_ticket"] = "Neues Ticket",
        ["shortcuts.tickets"] = "Ticket-Liste",
        ["shortcuts.kanban"] = "Kanban Board",
        ["shortcuts.dashboard"] = "Dashboard",
        ["shortcuts.reports"] = "Berichte",
        ["shortcuts.settings"] = "Einstellungen",
        ["shortcuts.search"] = "Suche fokussieren",
        ["shortcuts.help"] = "Diese Hilfe anzeigen",
        ["shortcuts.palette"] = "Befehlspalette öffnen",
        ["palette.placeholder"] = "Tickets suchen oder Aktion ausführen…",
        ["palette.no_results"] = "Keine Treffer.",
        ["palette.category_navigation"] = "Navigation",
        ["palette.category_actions"] = "Aktionen",
        ["palette.category_tickets"] = "Tickets",
        ["palette.subtitle_new_ticket"] = "Neues Ticket anlegen",
        ["palette.subtitle_toggle_dark"] = "Hell/Dunkel umschalten",
        ["palette.hint_navigate"] = "navigieren",
        ["palette.hint_select"] = "auswählen",
        ["palette.hint_close"] = "schließen",

        // Favorites
        ["nav.favorites"] = "Favoriten",
        ["favorites.empty"] = "Keine Favoriten. Markiere Tickets mit dem Stern-Symbol.",
        ["favorites.remove"] = "Aus Favoriten entfernen",
        ["favorites.removed"] = "Favorit entfernt.",

        // Advanced Search
        ["search.advanced"] = "Erweiterte Filter",
        ["search.date_from"] = "Von Datum",
        ["search.date_to"] = "Bis Datum",
        ["search.clear_filter"] = "Filter zurücksetzen",

        // Documents
        ["nav.documents"] = "Dokumente",
        ["documents.new"] = "Neues Dokument",
        ["documents.empty"] = "Keine Dokumente vorhanden.",
        ["documents.name"] = "Name",
        ["documents.description"] = "Beschreibung",
        ["documents.category"] = "Kategorie",
        ["documents.uploaded_by"] = "Hochgeladen von",
        ["documents.date"] = "Datum",
        ["documents.size"] = "Größe",
        ["documents.created"] = "Dokument erstellt.",
        ["documents.deleted"] = "Dokument gelöscht.",

        // Notices
        ["nav.notices"] = "Ankündigungen",
        ["notices.new"] = "Neue Ankündigung",
        ["notices.empty"] = "Keine Ankündigungen vorhanden.",
        ["notices.name"] = "Titel",
        ["notices.message"] = "Nachricht",
        ["notices.bg_color"] = "Hintergrundfarbe",
        ["notices.active"] = "Aktiv",
        ["notices.activate"] = "Aktivieren",
        ["notices.clear_all"] = "Alle deaktivieren",
        ["notices.created"] = "Ankündigung erstellt.",
        ["notices.activated"] = "Ankündigung aktiviert.",
        ["notices.cleared"] = "Alle Ankündigungen deaktiviert.",
        ["notices.deleted"] = "Ankündigung gelöscht.",

        // Accessibility
        ["a11y.toggle_menu"] = "Menü umschalten",
        ["a11y.notifications"] = "Benachrichtigungen",
        ["a11y.toggle_darkmode"] = "Dark Mode umschalten",
        ["a11y.logout"] = "Abmelden",
        ["a11y.main_navigation"] = "Hauptnavigation",

        // Statistics
        ["nav.statistics"] = "Statistik",
        ["stats.kpi_open"] = "Offene Tickets",
        ["stats.kpi_created"] = "Erstellt ({0} Tage)",
        ["stats.kpi_closed"] = "Geschlossen ({0} Tage)",
        ["stats.kpi_avg_response"] = "Ø Reaktionszeit",
        ["stats.volume_title"] = "Ticketaufkommen",
        ["stats.status_title"] = "Status-Verteilung",
        ["stats.workload_title"] = "Auslastung pro Bearbeiter",
        ["stats.timespan_days"] = "{0} Tage",
        ["stats.no_data"] = "Keine Daten verfügbar.",
        ["stats.open"] = "Offen",
        ["stats.closed"] = "Geschlossen",
    };

    private static readonly Dictionary<string, string> En = new()
    {
        // Navigation
        ["nav.dashboard"] = "Dashboard",
        ["nav.tickets"] = "Tickets",
        ["nav.newticket"] = "New Ticket",
        ["nav.kanban"] = "Kanban Board",
        ["nav.team"] = "Team",
        ["nav.reports"] = "Reports",
        ["nav.scanner"] = "Scanner",
        ["nav.notifications"] = "Notifications",
        ["nav.syncconflicts"] = "Sync Conflicts",
        ["nav.settings"] = "Settings",
        ["nav.bugreports"] = "Bug Reports",

        // Common
        ["common.save"] = "Save",
        ["common.cancel"] = "Cancel",
        ["common.delete"] = "Delete",
        ["common.edit"] = "Edit",
        ["common.close"] = "Close",
        ["common.open"] = "Open",
        ["common.print"] = "Print",
        ["common.popup_blocked"] = "Popup blocked — please allow popups for this site",
        ["common.search"] = "Search",
        ["common.filter"] = "Filter",
        ["common.refresh"] = "Refresh",
        ["common.loading"] = "Loading...",
        ["common.error"] = "Error",
        ["common.success"] = "Success",
        ["common.all"] = "All",
        ["common.yes"] = "Yes",
        ["common.no"] = "No",
        ["common.back"] = "Back",
        ["common.logout"] = "Logout",
        ["common.clear"] = "Clear",

        // Onboarding tour
        ["onboarding.step"] = "Step",
        ["onboarding.next"] = "Next",
        ["onboarding.skip"] = "Skip",
        ["onboarding.finish"] = "Let's go!",
        ["onboarding.step1_title"] = "Welcome to the THW Ticket App",
        ["onboarding.step1_body"] = "The next steps walk you through the key features. Takes about a minute — skippable any time via the X in the corner.",
        ["onboarding.step2_title"] = "Dashboard and ticket list",
        ["onboarding.step2_body"] = "The Dashboard shows open / in-progress / closed counts at a glance. Click any tile to filter the list. In the list you can search, sort, and filter by status, priority, group, etc.",
        ["onboarding.step3_title"] = "Create new tickets",
        ["onboarding.step3_body"] = "The blue plus button bottom-right opens the form from any page. Tip: what you type is auto-saved as a draft — nothing's lost if the browser crashes or you close the tab.",
        ["onboarding.step4_title"] = "Editing a ticket",
        ["onboarding.step4_body"] = "On the detail page: click the title or description to edit inline. The status / priority / group / assignee chips above are clickable — one tap opens a menu, another picks the new value. Comments and notes appear chronologically in the activity feed.",
        ["onboarding.step5_title"] = "Kanban board",
        ["onboarding.step5_body"] = "Kanban groups tickets by status. On desktop, drag cards between columns. On mobile, use the ↔ icon on a card to pick a new status. The 'My tickets' filter narrows to ones assigned to you.",
        ["onboarding.step6_title"] = "Quick search & keyboard",
        ["onboarding.step6_body"] = "Press Ctrl+K (or Cmd+K on Mac) on any page — the command palette opens. Type a ticket number or keyword, or navigate to any page. Press '?' to see all keyboard shortcuts; '/' jumps directly into the ticket list search.",
        ["onboarding.step7_title"] = "Sign in with Passkey",
        ["onboarding.step7_body"] = "In Settings → Passkey you can register this device. Then you sign in with fingerprint, face recognition, or device PIN — no password. If you enable Auto-Lock, the app locks itself after inactivity.",
        ["onboarding.step8_title"] = "Discover more",
        ["onboarding.step8_body"] = "Settings contains notifications, dark mode, language, theme color and more. You can re-open this tour any time via 'Show intro again' in Settings. Questions? Your OV admin can help.",
        ["settings.show_onboarding"] = "Show intro again",
        ["settings.show_whatsnew"] = "What's new?",
        ["whatsnew.title"] = "What's new?",
        ["whatsnew.dismiss"] = "Got it",
        ["settings.autosave_hint"] = "Changes are saved automatically.",
        ["settings.notifications_enable"] = "Enable notifications",
        ["settings.advanced"] = "Advanced",
        ["settings.advanced_warning"] = "These settings are for administrators only — wrong values can break the app.",
        ["settings.danger_zone"] = "Account",
        ["settings.logout_hint"] = "Ends your session on this device.",
        ["notifications.mark_all_read"] = "Mark all as read",
        ["notifications.mark_read"] = "Mark as read",
        ["notifications.mark_failed"] = "Could not mark as read.",
        ["notifications.marked_all"] = "{0} notifications marked as read.",

        // Login
        ["login.title"] = "Sign In",
        ["login.username"] = "Username",
        ["login.password"] = "Password",
        ["login.submit"] = "Sign In",
        ["login.submitting"] = "Signing in...",
        ["login.failed"] = "Login failed. Please check your username and password.",
        ["login.connection_error"] = "Connection error",
        ["login.passkey"] = "Sign in with Passkey",
        ["login.passkey_failed"] = "Passkey authentication failed.",
        ["login.passkey_cancelled"] = "Passkey authentication cancelled.",
        ["login.passkey_no_session"] = "Passkey OK, but no locked session found. Please sign in with username and password once — the Passkey button will work afterwards.",
        ["login.username_required"] = "Username is required",
        ["login.password_required"] = "Password is required",

        // Tickets
        ["tickets.title"] = "Tickets",
        ["tickets.new"] = "New Ticket",
        ["tickets.search"] = "Search tickets...",
        ["tickets.active"] = "Active",
        ["tickets.open"] = "Open",
        ["tickets.pending"] = "In Progress",
        ["tickets.closed"] = "Closed",
        ["tickets.mytickets"] = "My Tickets",
        ["tickets.sort"] = "Sort by",
        ["tickets.sort.newest"] = "Created (newest)",
        ["tickets.sort.oldest"] = "Created (oldest)",
        ["tickets.sort.updated"] = "Last updated",
        ["tickets.sort.priority"] = "Priority",
        ["tickets.sort.subject"] = "Subject (A-Z)",
        ["tickets.none"] = "No tickets found.",
        ["tickets.empty_description"] = "Create the first ticket — or adjust your filters if you expected some to be here.",
        ["tickets.assigned"] = "Ticket assigned.",
        ["tickets.closed_success"] = "Ticket closed.",
        ["tickets.savefilter"] = "Save Filter",
        ["tickets.loadfilter"] = "Saved Filters",
        ["tickets.deletefilter"] = "Delete Filter",
        ["tickets.filtername"] = "Filter name",

        // Markdown editor toolbar
        ["editor.toolbar"] = "Text formatting",
        ["editor.bold"] = "Bold",
        ["editor.italic"] = "Italic",
        ["editor.underline"] = "Underline",
        ["editor.strike"] = "Strikethrough",
        ["editor.code"] = "Code",
        ["editor.list"] = "List",
        ["editor.bold_placeholder"] = "bold text",
        ["editor.italic_placeholder"] = "italic text",
        ["editor.underline_placeholder"] = "underlined text",
        ["editor.strike_placeholder"] = "strikethrough text",
        ["editor.code_placeholder"] = "code",
        ["editor.list_placeholder"] = "list item",

        // Ticket Detail
        ["detail.description"] = "Description",
        ["detail.no_description"] = "No description.",
        ["detail.edit"] = "Edit ticket",
        ["detail.subject"] = "Subject",
        ["detail.status"] = "Status",
        ["detail.priority"] = "Priority",
        ["detail.creator"] = "Creator",
        ["detail.assignee"] = "Assignee",
        ["detail.unassigned"] = "Unassigned",
        ["detail.group"] = "Group",
        ["detail.type"] = "Type",
        ["detail.created"] = "Created",
        ["detail.updated"] = "Updated",
        ["detail.due"] = "Due",
        ["detail.no_due"] = "No date",
        ["detail.assign_to"] = "Assign to",
        ["detail.assign"] = "Assign",
        ["detail.remove_assign"] = "Remove",
        ["detail.tags"] = "Tags",
        ["detail.linked"] = "Linked Tickets",
        ["detail.no_links"] = "No links.",
        ["detail.link_related"] = "Related",
        ["detail.link_blocks"] = "Blocks",
        ["detail.link_blocked_by"] = "Blocked by",
        ["detail.link_duplicate"] = "Duplicate",
        ["detail.subscribe"] = "Subscribe",
        ["detail.unsubscribe"] = "Unsubscribe",
        ["detail.subscribed"] = "Subscribed to ticket.",
        ["detail.unsubscribed"] = "Unsubscribed from ticket.",
        ["detail.delete_ticket"] = "Delete ticket",
        ["detail.not_found"] = "Ticket not found.",

        // Comments & Notes
        ["comments.title"] = "Comments",
        ["comments.new"] = "New comment",
        ["comments.send"] = "Send comment",
        ["comments.added"] = "Comment added.",
        ["comments.preview_toggle"] = "Toggle Markdown preview",
        ["comments.preview_on"] = "Preview",
        ["comments.preview_off"] = "Edit",
        ["comments.preview_empty"] = "Type something to see the preview.",
        ["attachments.drop_hint"] = "or drop files here",
        ["comments.quickreply"] = "Insert quick reply",
        ["comments.mention"] = "Mention",
        ["notes.title"] = "Notes",
        ["notes.new"] = "New note",
        ["notes.add"] = "Add note",
        ["notes.added"] = "Note added.",
        ["offline.queued"] = "Saved offline — will sync when the connection is back.",
        ["offline.action_unavailable"] = "This action requires an online connection.",

        // Attachments
        ["attachments.title"] = "Attachments",
        ["attachments.none"] = "No attachments.",
        ["attachments.upload"] = "Upload file",
        ["attachments.take_photo"] = "Take photo",
        ["attachments.uploading"] = "Uploading...",
        ["attachments.uploaded"] = "File uploaded.",
        ["attachments.deleted"] = "Attachment deleted.",
        ["attachments.dsgvo_hint"] = "Please don't photograph people without consent. Images are compressed to max. 2400 px server-side.",
        ["attachments.name"] = "Name",
        ["attachments.type"] = "Type",
        ["attachments.size"] = "Size",
        ["attachments.date"] = "Date",
        ["attachments.actions"] = "Actions",

        // Time Tracking
        ["time.title"] = "Time Tracking",
        ["time.timer"] = "Timer",
        ["time.start"] = "Start",
        ["time.stop"] = "Stop",
        ["time.description"] = "Description (optional)",
        ["time.total"] = "Total",
        ["time.no_entries"] = "No time entries.",
        ["time.col_start"] = "Start",
        ["time.col_duration"] = "Duration",
        ["time.col_description"] = "Description",

        // History
        ["history.title"] = "History",

        // Assets
        ["nav.assets"] = "Assets",
        ["assets.new"] = "New Asset",
        ["assets.name"] = "Name",
        ["assets.tag"] = "Asset Tag",
        ["assets.category"] = "Category",
        ["assets.location"] = "Location",
        ["assets.none"] = "No assets found.",
        ["assets.name_required"] = "Name is required.",
        ["assets.delete_confirm"] = "Really delete asset",
        ["assets.link_ticket"] = "Link to ticket",
        ["assets.link_ticket_prompt"] = "Ticket number",
        ["assets.link_ticket_empty"] = "Please enter a ticket number.",
        ["assets.link_ticket_success"] = "Asset linked to ticket.",
        ["assets.link_ticket_failed"] = "Linking failed.",

        // Templates
        ["nav.templates"] = "Ticket Templates",
        ["templates.new"] = "New Template",
        ["templates.none"] = "No templates yet.",
        ["templates.empty_description"] = "Create templates to spin up recurring tickets faster.",
        ["templates.name"] = "Name",
        ["templates.subject"] = "Subject",
        ["templates.issue"] = "Description",
        ["templates.issue_preview"] = "Description",
        ["templates.name_required"] = "Name is required.",
        ["templates.subject_required"] = "Subject is required.",
        ["templates.delete_confirm"] = "Really delete template?",
        ["templates.checklist"] = "Checklist",
        ["templates.checklist_add"] = "Add item",
        ["templates.checklist_hint"] = "Copied onto the ticket when the template is applied",

        // Calendar
        ["nav.calendar"] = "Calendar",
        ["calendar.from"] = "From",
        ["calendar.to"] = "To",
        ["calendar.load"] = "Load",
        ["calendar.this_month"] = "Current month",
        ["calendar.none"] = "No events in the selected range.",
        ["calendar.empty_description"] = "Events from tickets with due dates show up here automatically.",
        ["calendar.range_required"] = "Please pick a start and end date.",
        ["calendar.range_invalid"] = "End date must be after start date.",
        ["calendar.ticket_deadline"] = "Ticket deadline",
        ["calendar.recurring_task"] = "Recurring task",
        ["calendar.open_ticket"] = "Open ticket",

        // Recurring Tasks
        ["nav.recurring"] = "Recurring Tasks",
        ["recurring.new"] = "New Task",
        ["recurring.active"] = "Active",
        ["recurring.inactive"] = "Inactive",
        ["recurring.schedule"] = "Schedule",
        ["recurring.ticket_subject"] = "Ticket Subject",
        ["recurring.ticket_template"] = "Ticket Template",
        ["recurring.schedule_type"] = "Recurrence Type",
        ["recurring.monthly"] = "Monthly",
        ["recurring.quarterly"] = "Quarterly",
        ["recurring.annual"] = "Annual",
        ["recurring.day_of_month"] = "Day of Month",
        ["recurring.days_before"] = "Days before deadline",
        ["recurring.enabled"] = "Enabled",
        ["recurring.next_run"] = "Next Run",
        ["recurring.none"] = "No recurring tasks.",
        ["recurring.name_required"] = "Name is required.",
        ["recurring.refs_required"] = "Please select a type, priority and group.",
        ["recurring.delete_confirm"] = "Really delete task",

        // Reports
        ["reports.handover"] = "Handover Report",
        ["reports.sitzung"] = "Meeting Report",
        ["reports.generate"] = "Generate report",
        ["reports.copy"] = "Copy to clipboard",
        ["reports.copied"] = "Report copied.",
        ["reports.copy_failed"] = "Copy failed.",
        ["reports.download_md"] = "Download as Markdown",
        ["reports.print"] = "Print / Save as PDF",

        // Settings
        ["settings.title"] = "Settings",
        ["settings.appearance"] = "Appearance",
        ["settings.darkmode"] = "Dark Mode",
        ["settings.notifications"] = "Notifications",
        ["settings.notifications_desc"] = "Get notified about new tickets and changes",
        ["settings.notify_new"] = "New tickets",
        ["settings.notify_comments"] = "Comments",
        ["settings.notify_status"] = "Status changes",
        ["settings.notify_mine"] = "My tickets only",
        ["settings.notify_mine_desc"] = "Only for tickets assigned to me",
        ["settings.notify_highprio"] = "High priority only",
        ["settings.notify_highprio_desc"] = "Only for high/urgent priority",
        ["settings.language"] = "Language / Sprache",
        ["settings.api"] = "API Configuration",
        ["settings.api_url"] = "Server URL",
        ["settings.timeout"] = "Connection timeout (seconds)",
        ["settings.test_connection"] = "Test connection",
        ["settings.testing"] = "Testing...",
        ["settings.cache"] = "Offline Cache",
        ["settings.cache_enable"] = "Enable offline caching",
        ["settings.cache_desc"] = "Store tickets locally for offline access",
        ["settings.cache_clear"] = "Clear cache",
        ["settings.saved"] = "Settings saved.",
        ["settings.passkey"] = "Passkey / Biometrics",
        ["settings.passkey_register"] = "Register Passkey",
        ["settings.passkey_registered"] = "Passkey registered",
        ["settings.passkey_remove"] = "Remove Passkey",
        ["settings.passkey_desc"] = "Quick sign-in via fingerprint, face, or device PIN",
        ["settings.passkey_not_supported"] = "Your browser does not support passkeys.",
        ["settings.passkey_register_failed"] = "Passkey registration failed.",
        ["settings.passkey_removed"] = "Passkey removed.",
        ["settings.idlelock"] = "Auto-lock",
        ["settings.idlelock_desc"] = "Lock the app after a period of inactivity. Unlock with passkey/biometrics. Requires a registered passkey.",
        ["settings.idlelock_enable"] = "Enable auto-lock",
        ["settings.idlelock_timeout"] = "Lock after",
        ["settings.idlelock_needs_passkey"] = "A passkey must be registered for auto-lock to work.",
        ["idlelock.locked"] = "App locked due to inactivity.",
        ["settings.timeout_invalid"] = "Timeout must be between 5 and 300 seconds.",
        ["settings.connection_testing"] = "Testing connection...",
        ["settings.connection_success"] = "Connection successful!",
        ["settings.connection_timeout"] = "Timeout. Server is not responding.",
        ["settings.connection_failed"] = "Connection failed. Server unreachable.",
        ["settings.cache_cleared"] = "Cache cleared.",
        ["settings.theme_color"] = "Accent Color",
        ["settings.about"] = "About",
        ["settings.sync"] = "Sync Conflicts",
        ["settings.sync_resolve"] = "Manage conflicts",
        ["settings.push_enable"] = "Push Notifications",
        ["settings.push_desc"] = "Deliver notifications even when the app is closed.",
        ["settings.push_enable_failed"] = "Couldn't enable push (permission denied or server unreachable).",
        ["settings.push_disable_failed"] = "Couldn't disable push.",
        ["bugreport.fab"] = "Report a bug",
        ["bugreport.title"] = "Report a bug",
        ["bugreport.intro"] = "Briefly describe what's broken. We'll attach the build version, current page and the last few browser console messages automatically.",
        ["bugreport.field_title"] = "Short summary",
        ["bugreport.field_description"] = "What happened? Steps to reproduce?",
        ["bugreport.context_hint"] = "Technical context (build, URL, user agent, console tail) is attached automatically.",
        ["bugreport.submit"] = "Submit",
        ["bugreport.sent"] = "Bug report submitted — admins are being notified.",
        ["bugreport.failed"] = "Submit failed. Please try again later.",
        ["bugreport.admin_title"] = "Bug Reports",
        ["bugreport.empty"] = "No bug reports.",
        ["bugreport.count"] = "{0} open / {1} total",
        ["bugreport.from"] = "From:",
        ["bugreport.context"] = "Technical context",
        ["bugreport.resolved"] = "Resolved",
        ["bugreport.mark_resolved"] = "Mark as resolved",
        ["bugreport.reopen"] = "Reopen",
        ["bugreport.resolved_ok"] = "Marked as resolved.",
        ["bugreport.reopened_ok"] = "Reopened.",
        ["bugreport.deleted"] = "Bug report deleted.",
        ["settings.update_check"] = "Check for updates",
        ["settings.update_checking"] = "Checking...",
        ["settings.update_uptodate"] = "Already up to date.",
        ["settings.update_failed"] = "Update check failed.",
        ["settings.synclog"] = "Sync Log",
        ["settings.synclog_desc"] = "Offline synchronization activity log",
        ["settings.synclog_empty"] = "No log entries.",
        ["settings.synclog_export"] = "Export log",
        ["settings.synclog_clear"] = "Clear log",
        ["settings.synclog_cleared"] = "Sync log cleared.",
        ["settings.synclog_time"] = "Time",
        ["settings.synclog_level"] = "Level",
        ["settings.synclog_action"] = "Action",
        ["settings.synclog_message"] = "Message",

        // Batch
        ["batch.toggle"] = "Multi-select",
        ["batch.selected"] = "{0} ticket(s) selected",
        ["batch.empty"] = "No tickets selected",
        ["batch.select_all_visible"] = "Select all on this page",
        ["batch.change_status"] = "Change status",
        ["batch.deleted"] = "{0} deleted, {1} failed",
        ["batch.updated"] = "{0} updated, {1} failed",
        ["batch.status_changed"] = "{0} changed to '{1}', {2} failed",
        ["tickets.change_status"] = "Change status…",
        ["tickets.status_changed"] = "Status changed to '{0}'.",
        ["detail.print"] = "Print / Save as PDF",
        ["detail.show_qr"] = "Show QR code",
        ["detail.print_qr"] = "Print QR code",

        // Profile
        ["nav.profile"] = "Profile",
        ["profile.title"] = "Profile",
        ["profile.info"] = "Personal Information",
        ["profile.fullname"] = "Full Name",
        ["profile.job_title"] = "Job Title",
        ["profile.work_number"] = "Work Phone",
        ["profile.mobile_number"] = "Mobile Number",
        ["profile.username"] = "Username",
        ["profile.email"] = "Email",
        ["profile.saved"] = "Profile saved.",
        ["profile.load_failed"] = "Could not load profile. Please try again later.",
        ["profile.avatar_pick"] = "Change picture",
        ["profile.avatar_uploading"] = "Uploading…",
        ["profile.avatar_saved"] = "Profile picture updated.",
        ["profile.avatar_failed"] = "Could not upload profile picture.",
        ["profile.avatar_too_large"] = "Image is too large (max 5 MB).",
        ["profile.avatar_offline"] = "Profile picture can only be changed online.",
        ["profile.change_password"] = "Change Password",
        ["profile.current_password"] = "Current Password",
        ["profile.new_password"] = "New Password",
        ["profile.confirm_password"] = "Confirm Password",
        ["profile.update_password"] = "Change Password",
        ["profile.password_changed"] = "Password changed.",
        ["profile.password_required"] = "Please fill in all password fields.",
        ["profile.password_mismatch"] = "Passwords do not match.",
        ["profile.password_too_short"] = "Password must be at least 6 characters.",
        ["profile.password_failed"] = "Password change failed.",
        ["profile.sessions_title"] = "Active Sessions",
        ["profile.sessions_subtitle"] = "Devices currently signed in to your account.",
        ["profile.sessions_empty"] = "No active sessions found.",
        ["profile.sessions_current"] = "This device",
        ["profile.sessions_legacy"] = "Legacy",
        ["profile.sessions_legacy_label"] = "Legacy token (pre multi-device)",
        ["profile.sessions_unknown_device"] = "Unknown device",
        ["profile.sessions_last_seen"] = "Last seen",
        ["profile.sessions_created"] = "Created",
        ["profile.sessions_revoke"] = "Sign out",
        ["profile.sessions_revoke_title"] = "Sign out this device?",
        ["profile.sessions_revoke_confirm"] = "This device will be signed out immediately.",
        ["profile.sessions_revoke_others"] = "Sign out all other devices",
        ["profile.sessions_revoke_others_title"] = "Sign out all other devices?",
        ["profile.sessions_revoke_others_confirm"] = "All other sessions will end immediately. This device stays signed in.",
        ["profile.sessions_revoked"] = "Session ended.",
        ["profile.sessions_revoke_failed"] = "Sign out failed.",
        ["profile.my_data_title"] = "My Data",
        ["profile.my_data_subtitle"] = "Access to your stored personal data (Art. 15 GDPR).",
        ["profile.export_data"] = "Export my data (GDPR)",
        ["profile.export_failed"] = "Export failed. Please try again later.",
        ["profile.export_offline"] = "The data export is not available offline.",

        // PWA
        ["pwa.install_hint"] = "Add app to home screen for faster access.",
        ["pwa.install"] = "Install",

        // Notifications (browser)
        ["notify.ticket_created"] = "New Ticket",
        ["notify.ticket_created_body"] = "Ticket #{0} was created.",
        ["notify.ticket_updated"] = "Ticket Updated",
        ["notify.ticket_updated_body"] = "Ticket #{0} was changed.",
        ["notify.status_changed"] = "Status Changed",
        ["notify.status_changed_body"] = "Status of ticket #{0} was changed.",
        ["notify.assignee_changed"] = "Assignment Changed",
        ["notify.assignee_changed_body"] = "Assignment of ticket #{0} was changed.",
        ["notify.comment_added"] = "New Comment",
        ["notify.comment_added_body"] = "New comment on ticket #{0}.",
        ["notify.ticket_event"] = "Ticket Event",
        ["notify.ticket_event_body"] = "Change on ticket #{0}.",

        // Kanban
        ["kanban.board"] = "Kanban board",
        ["kanban.tickets"] = "tickets",
        ["kanban.ticket_moved"] = "Ticket moved",
        ["kanban.move_failed"] = "Status change failed.",
        ["kanban.status_not_allowed"] = "Status \"{0}\" is not allowed for type \"{1}\".",
        ["kanban.move_to"] = "Change status",
        ["kanban.column_empty"] = "No tickets in this column.",
        ["kanban.no_subject"] = "(No subject)",
        ["common.unknown"] = "Unknown",
        ["common.or"] = "or",
        ["common.network_error"] = "Network error. Please try again.",

        // Ticket Detail (additional)
        ["detail.details"] = "Details",
        ["detail.activity"] = "Activity",
        ["detail.activity_comments_notes"] = "Comments & Notes",
        ["detail.activity_history"] = "History",
        ["detail.activity_empty"] = "No activity yet. Write the first comment or note below.",
        ["detail.activity_internal"] = "Internal",
        ["detail.click_to_edit"] = "Click to edit",
        ["detail.composer_comment"] = "Comment",
        ["detail.composer_note"] = "Note",
        ["detail.composer_open"] = "Write a comment or note",
        ["detail.composer_close"] = "Close",
        ["detail.note_visible_internal"] = "Notes are only visible to agents, not to the ticket creator.",
        ["detail.no_group"] = "No group",
        ["detail.no_assignees_available"] = "No assignable users — likely a permission issue.",
        ["detail.favorite"] = "Favorite",
        ["time.entries_short"] = "entries",
        ["detail.ticket_updated"] = "Ticket updated.",
        ["detail.update_failed"] = "Update failed.",
        ["detail.assign_updated"] = "Assignment updated.",
        ["detail.assign_failed"] = "Assignment failed.",
        ["detail.assign_removed"] = "Assignment removed.",
        ["detail.additional_assignees"] = "Additional assignees",
        ["detail.additional_assignees_add"] = "Add person",
        ["detail.add_failed"] = "Failed to add.",
        ["detail.delete_failed"] = "Delete failed.",
        ["detail.ticket_deleted"] = "Ticket deleted.",
        ["detail.templates_saved"] = "Templates saved.",
        ["detail.edit_templates"] = "Edit templates",
        ["detail.quickreply_templates"] = "Quick reply templates",
        ["detail.new_template"] = "New",
        ["detail.link_ticket_num"] = "Ticket #",
        ["common.add"] = "Add",

        // Checklist
        ["checklist.title"] = "Checklist",
        ["checklist.empty"] = "No items.",
        ["checklist.new_item"] = "New item",

        ["detail.add_tag"] = "Add tag",
        ["detail.tag_added"] = "Tag added",
        ["detail.tag_removed"] = "Tag removed.",

        // Tickets (additional)
        ["tickets.assign_me"] = "Assign to me",
        ["tickets.actions"] = "Ticket actions",
        ["tickets.assign_failed"] = "Assignment failed.",
        ["tickets.close_failed"] = "Close failed.",
        ["tickets.filter_saved"] = "Filter saved.",
        ["tickets.filter_deleted"] = "Filter deleted.",
        ["tickets.create_title"] = "Create new ticket",
        ["tickets.subject_required"] = "Subject is required",
        ["tickets.description_required"] = "Description is required",
        ["tickets.group_required"] = "Group is required",
        ["tickets.create"] = "Create ticket",
        ["tickets.export_csv"] = "Export as CSV",
        ["tickets.use_template"] = "Use template",
        ["tickets.form_load_error"] = "Failed to load form data.",
        ["tickets.no_visible_groups"] = "You are not assigned to any group — please contact an admin.",
        ["tickets.created"] = "Ticket created!",
        ["tickets.server_rejected"] = "Server rejected the ticket.",
        ["tickets.draft_restored"] = "Draft restored — pick up where you left off.",
        ["tickets.draft_discard"] = "Discard",
        ["tickets.attachments_label"] = "Attachments (optional)",
        ["tickets.attachments_pick"] = "Choose files",
        ["tickets.attachments_selected"] = "{0} file(s) selected",
        ["tickets.attachments_remove"] = "Remove",
        ["tickets.attachments_too_large"] = "{0} is too large (max. 25 MB).",
        ["tickets.attachments_uploading"] = "Uploading attachments…",
        ["tickets.attachments_partial"] = "Ticket created, but {0} of {1} attachments failed to upload.",
        ["tickets.attachments_offline"] = "Offline — {0} attachment(s) could not be included. Please add them to the ticket later.",
        ["tickets.template_checklist_info"] = "{0} checklist items will be applied",

        // Dashboard
        ["dashboard.total"] = "Total",
        ["dashboard.open"] = "Open",
        ["dashboard.in_progress"] = "In Progress",
        ["dashboard.closed"] = "Closed",
        ["dashboard.mine"] = "Mine",
        ["dashboard.overdue"] = "Overdue",
        ["dashboard.recent"] = "Recent Tickets",
        ["dashboard.view_all"] = "View all",
        ["dashboard.no_tickets"] = "No tickets found.",
        ["dashboard.quick_actions"] = "Quick Actions",
        ["dashboard.tickets_per_group"] = "Tickets per Group",
        ["dashboard.open_suffix"] = "open",
        ["dashboard.welcome"] = "Welcome!",
        ["dashboard.welcome_user"] = "Welcome",
        ["dashboard.recently_visited"] = "Recently visited",
        ["time.just_now"] = "just now",
        ["time.minutes_ago"] = "min ago",
        ["time.hours_ago"] = "h ago",
        ["time.days_ago"] = "d ago",
        ["dashboard.beschluesse"] = "Open Resolutions",
        ["dashboard.upcoming_tasks"] = "Upcoming Tasks",
        ["dashboard.assets_total"] = "Total Assets",

        // Login (additional)
        ["login.configure_server"] = "Please configure the server URL first.",
        ["login.server_config"] = "Server Configuration",
        ["login.server_url"] = "Server URL",
        ["login.save_url"] = "Save URL",
        ["login.invalid_url"] = "Please enter a valid server URL.",
        ["login.passkey_cancelled"] = "Passkey authentication cancelled.",
        ["login.register_link"] = "No account yet? Register now",

        // Registration
        ["register.title"] = "Create Account",
        ["register.fullname"] = "Full Name",
        ["register.fullname_required"] = "Name is required (at least 5 characters)",
        ["register.username"] = "Username",
        ["register.username_required"] = "Username is required (3–50 characters)",
        ["register.username_hint"] = "3–50 characters: letters, digits, dot, dash, underscore",
        ["register.email"] = "Email Address",
        ["register.email_required"] = "Email is required",
        ["register.password"] = "Password",
        ["register.password_required"] = "Password is required",
        ["register.password_hint"] = "At least 8 characters with 3 different types: lowercase, uppercase, digits, special characters",
        ["register.password_confirm"] = "Confirm Password",
        ["register.password_mismatch"] = "Passwords do not match",
        ["register.captcha"] = "Security Code",
        ["register.captcha_required"] = "Security code is required",
        ["register.captcha_hint"] = "Enter the code from the image (case-sensitive)",
        ["register.captcha_refresh"] = "Load new code",
        ["register.captcha_error"] = "Could not load security code",
        ["register.submit"] = "Create Account",
        ["register.submitting"] = "Creating...",
        ["register.success"] = "Account created successfully! You can now sign in.",
        ["register.failed"] = "Registration failed",
        ["register.email_exists"] = "This email address is already in use.",
        ["register.username_exists"] = "This username is already taken.",
        ["register.disabled"] = "Registration is currently disabled.",
        ["register.login_link"] = "Already have an account? Sign in",
        ["register.invalid_captcha"] = "Security code incorrect. Please try again.",

        // Scanner
        ["scanner.instruction"] = "Scan a QR code or barcode to open a ticket.",
        ["scanner.not_supported"] = "Your browser does not support the BarcodeDetector API. Please enter the ticket number manually.",
        ["scanner.start_camera"] = "Start camera",
        ["scanner.stop_camera"] = "Stop camera",
        ["scanner.manual_input"] = "Manual input",
        ["scanner.ticket_number"] = "Ticket number",
        ["scanner.open_ticket"] = "Open",
        ["scanner.camera_failed"] = "Camera could not be started.",
        ["scanner.detected"] = "Detected",

        // Sync Conflicts
        ["sync.no_conflicts"] = "No sync conflicts.",
        ["sync.conflicts_found"] = "{0} conflicts found. Please decide for each action whether to force-apply or discard.",
        ["sync.force_apply"] = "Force apply",
        ["sync.discard"] = "Discard",
        ["sync.applied"] = "Action applied successfully.",
        ["sync.apply_failed"] = "Action could not be applied.",
        ["sync.discarded"] = "Action discarded.",
        ["sync.type_deleted"] = "Ticket deleted",
        ["sync.type_permission"] = "No permission",
        ["sync.type_status"] = "Status already changed",
        ["sync.type_updated"] = "Ticket updated",
        ["sync.type_conflict"] = "Conflict",
        ["sync.advice_deleted"] = "The ticket no longer exists on the server, so the action can only be discarded.",
        ["sync.advice_permission"] = "Your permission for this ticket was revoked. Please contact an administrator.",
        ["sync.advice_status"] = "Someone else changed the status in the meantime. Forcing will overwrite that value.",
        ["sync.action_add_comment"] = "Add comment",
        ["sync.action_add_note"] = "Add note",
        ["sync.action_assign"] = "Assign ticket",
        ["sync.action_update_status"] = "Change status",
        ["sync.action_create"] = "Create new ticket",
        ["sync.action_clear_assignee"] = "Remove assignment",
        ["sync.action_set_additional_assignees"] = "Change additional assignees",
        ["sync.action_update_fields"] = "Update ticket fields",
        ["sync.action_delete"] = "Delete ticket",
        ["sync.action_upload"] = "Upload attachment",

        // Team
        ["team.members"] = "Members",
        ["team.tickets_per_person"] = "Tickets/Person",
        ["team.tickets_30d"] = "Tickets (30d)",
        ["team.closed"] = "Closed",
        ["team.response_time"] = "Response time",
        ["team.overdue"] = "Overdue",
        ["team.most_requests"] = "Most requests",
        ["team.most_assignments"] = "Most assignments",
        ["team.workload"] = "Team workload",
        ["team.no_members"] = "No team members found.",
        ["team.assigned"] = "Assigned",
        ["team.open"] = "Open",
        ["team.workload_col"] = "Workload",
        ["team.workload_high"] = "High",
        ["team.workload_medium"] = "Medium",
        ["team.workload_normal"] = "Normal",

        // Notifications
        ["notifications.unread"] = "Unread",
        ["notifications.read"] = "Read",
        ["notifications.none"] = "No notifications.",
        ["notifications.default_title"] = "Notification",
        ["notifications.load_more"] = "Load more",

        // Reports
        ["reports.weekly_trend"] = "Ticket Trend (last 8 weeks)",
        ["reports.created"] = "Created",
        ["reports.closed"] = "Closed",
        ["reports.no_data"] = "No data available.",
        ["reports.resolution_times"] = "Resolution Times",
        ["reports.resolved"] = "Resolved Tickets",
        ["reports.average"] = "Average",
        ["reports.fastest"] = "Fastest",
        ["reports.slowest"] = "Slowest",
        ["reports.sla_compliance"] = "SLA Compliance",
        ["reports.sla_met"] = "Met",
        ["reports.sla_breached"] = "Breached",
        ["reports.sla_at_risk"] = "At Risk",
        ["reports.no_deadline"] = "No deadline",
        ["reports.priority_dist"] = "Priority Distribution",
        ["reports.top_assignees"] = "Top Assignees",
        ["reports.no_deadline_tickets"] = "No tickets with due date",

        // Keyboard Shortcuts
        ["shortcuts.title"] = "Keyboard Shortcuts",
        ["shortcuts.new_ticket"] = "New Ticket",
        ["shortcuts.tickets"] = "Ticket List",
        ["shortcuts.kanban"] = "Kanban Board",
        ["shortcuts.dashboard"] = "Dashboard",
        ["shortcuts.reports"] = "Reports",
        ["shortcuts.settings"] = "Settings",
        ["shortcuts.search"] = "Focus Search",
        ["shortcuts.help"] = "Show this help",
        ["shortcuts.palette"] = "Open command palette",
        ["palette.placeholder"] = "Search tickets or run a command…",
        ["palette.no_results"] = "No matches.",
        ["palette.category_navigation"] = "Navigation",
        ["palette.category_actions"] = "Actions",
        ["palette.category_tickets"] = "Tickets",
        ["palette.subtitle_new_ticket"] = "Create a new ticket",
        ["palette.subtitle_toggle_dark"] = "Toggle light/dark",
        ["palette.hint_navigate"] = "navigate",
        ["palette.hint_select"] = "select",
        ["palette.hint_close"] = "close",

        // Favorites
        ["nav.favorites"] = "Favorites",
        ["favorites.empty"] = "No favorites yet. Star tickets to add them here.",
        ["favorites.remove"] = "Remove from favorites",
        ["favorites.removed"] = "Favorite removed.",

        // Advanced Search
        ["search.advanced"] = "Advanced Filters",
        ["search.date_from"] = "From Date",
        ["search.date_to"] = "To Date",
        ["search.clear_filter"] = "Clear Filters",

        // Documents
        ["nav.documents"] = "Documents",
        ["documents.new"] = "New Document",
        ["documents.empty"] = "No documents yet.",
        ["documents.name"] = "Name",
        ["documents.description"] = "Description",
        ["documents.category"] = "Category",
        ["documents.uploaded_by"] = "Uploaded by",
        ["documents.date"] = "Date",
        ["documents.size"] = "Size",
        ["documents.created"] = "Document created.",
        ["documents.deleted"] = "Document deleted.",

        // Notices
        ["nav.notices"] = "Notices",
        ["notices.new"] = "New Notice",
        ["notices.empty"] = "No notices yet.",
        ["notices.name"] = "Title",
        ["notices.message"] = "Message",
        ["notices.bg_color"] = "Background Color",
        ["notices.active"] = "Active",
        ["notices.activate"] = "Activate",
        ["notices.clear_all"] = "Clear All",
        ["notices.created"] = "Notice created.",
        ["notices.activated"] = "Notice activated.",
        ["notices.cleared"] = "All notices deactivated.",
        ["notices.deleted"] = "Notice deleted.",

        // Accessibility
        ["a11y.toggle_menu"] = "Toggle menu",
        ["a11y.notifications"] = "Notifications",
        ["a11y.toggle_darkmode"] = "Toggle dark mode",
        ["a11y.logout"] = "Log out",
        ["a11y.main_navigation"] = "Main navigation",

        // Statistics
        ["nav.statistics"] = "Statistics",
        ["stats.kpi_open"] = "Open Tickets",
        ["stats.kpi_created"] = "Created ({0} days)",
        ["stats.kpi_closed"] = "Closed ({0} days)",
        ["stats.kpi_avg_response"] = "Avg. Response Time",
        ["stats.volume_title"] = "Ticket Volume",
        ["stats.status_title"] = "Status Distribution",
        ["stats.workload_title"] = "Workload per Agent",
        ["stats.timespan_days"] = "{0} days",
        ["stats.no_data"] = "No data available.",
        ["stats.open"] = "Open",
        ["stats.closed"] = "Closed",
    };
}
